import os
import sys
import glob

options_filename = 'options.cache'
options = Variables(options_filename, ARGUMENTS)
options.Add(PathVariable('clam_prefix', 'The prefix where CLAM was installed', ''))
options.Add(BoolVariable('release', 'Build CLAM Annotator enabling compiler optimizations', 'no') )
options.Add(BoolVariable('verbose', 'Display the full command line instead a short command description', 'no') )
if sys.platform=="linux" :
	options.Add(BoolVariable('crossmingw', 'Using MinGW crosscompiler mode', 'no') )

def scanFiles(pattern, paths) :
	files = []
	for path in paths :
		files+=glob.glob(path+"/"+pattern)
	return files

def recursiveDirs(root) :
	return filter( (lambda a : a.rfind( ".svn")==-1 ),  [ a[0] for a in os.walk(root)]  )

def unique(list) :
	return dict.fromkeys(list).keys()

toolchain='default'
if sys.platform == 'win32': toolchain = 'mingw'
env = Environment(ENV=os.environ, tools=[toolchain], options=options)
options.Update(env)
options.Save('options.cache', env)
Help(options.GenerateHelpText(env))

env.SConsignFile() # Single signature file

crosscompiling = env.get("crossmingw")
isWindowsPlatform = sys.platform=='win32' or crosscompiling
isLinuxPlatform = sys.platform=='linux' and not crosscompiling
isDarwinPlatform = sys.platform=='darwin'

CLAMInstallDir = env['clam_prefix']
clam_sconstoolspath = os.path.join(CLAMInstallDir,'share','clam','sconstools')

env.Tool('qt6', toolpath=[clam_sconstoolspath])
env.Tool('clam', toolpath=[clam_sconstoolspath])
env.Tool('nsis', toolpath=[clam_sconstoolspath])
if crosscompiling :
	env.Tool('crossmingw', toolpath=[clam_sconstoolspath])


env['CXXFILESUFFIX'] = '.cxx'
env['QT6_UICDECLSUFFIX'] = '.h'
env.moveIntermediateInto('generated')
env.activateColorCommandLine()
if not env['verbose']: env.ClamQuietCompilation()

env.EnableQt6Modules([
	'QtCore',
	'QtGui',
	'QtWidgets',
	'QtOpenGL',
	'QtOpenGLWidgets',
	],
	debug=False,
	crosscompiling=crosscompiling,
	)

env.EnableClamModules([
	'clam_core',
	'clam_audioio',
	'clam_processing',
	], CLAMInstallDir)

libSourcePaths = []
libSourcePaths += recursiveDirs("plot")
libSourcePaths += recursiveDirs("render")
libSourcePaths += recursiveDirs("data")
libSourcePaths += recursiveDirs("util")
libSourcePaths += recursiveDirs("player")
libSourcePaths += recursiveDirs("misc")
libSourcePaths += recursiveDirs("widget")
extraPaths = []
extraPaths += recursiveDirs("examples/utils")
extraPaths += [
	CLAMInstallDir+'/include',
	CLAMInstallDir+'/include/CLAM', # KLUDGE to keep old style includes	
]
includePaths = libSourcePaths + extraPaths

sources = env.scanFiles('*.cxx', libSourcePaths,
	patternblacklist=['moc_','qrc_'],
	)

qrcfiles = env.scanFiles("*.qrc", libSourcePaths)
if qrcfiles : sources += env.Qrc(source=qrcfiles)

uifiles = env.scanFiles("*.qt6.ui", libSourcePaths)
if uifiles : uiheaders = env.Uic6(source=uifiles)


env.Append(CPPPATH=includePaths)

env.ParseConfig('pkg-config gl --libs --cflags')

examplesMainSources = [
	"examples/src/audio_plot_example.cxx",
	"examples/src/fundamental_plot_example.cxx",
	"examples/src/segmentation_plot_example.cxx",
	"examples/src/sintracks_plot_example.cxx",
	"examples/src/spectrum_plot_example.cxx",
	"examples/src/spectrogram_plot_example.cxx",
	"examples/src/audio_stereo_plot_example.cxx",
	"examples/src/bpf_plot_example.cxx",
	"examples/src/multibpf_plot_example.cxx",
	"examples/src/playable_audio_plot_example.cxx",
	"examples/src/playable_audio_stereo_plot_example.cxx",
	"examples/src/playable_bpf_plot_example.cxx",
	"examples/src/playable_fundamental_plot_example.cxx",
	"examples/src/playable_multibpf_plot_example.cxx",
]

if sys.platform=='darwin' :
	env.AppendUnique(CXXFLAGS="-F"+os.path.join(env['QTDIR'],'lib'))
	env.AppendUnique(LINKFLAGS="-F"+os.path.join(env['QTDIR'],'lib'))
	env.AppendUnique(LINKFLAGS='-framework QtCore')
	env.AppendUnique(LINKFLAGS='-framework QtGui')
	env.AppendUnique(LINKFLAGS='-framework QtOpenGL')
	env.AppendUnique(LINKFLAGS='-dynamic')
#	env.AppendUnique(FRAMEWORKPATH=[os.path.join(env['QTDIR'],'lib')])
#	env.AppendUnique(FRAMEWORKS=['QtCore','QtGui','QtOpenGL'])

exampleSources = scanFiles('*.cxx', ['examples/utils'])

env.Append( CCFLAGS=['-g','-O3','-fomit-frame-pointer','-Wall'] )
staticLibrary = env.StaticLibrary(target='clam_vmqt6', source=sources)
env.Append(LIBPATH='.')
env.Prepend(LIBS='clam_vmqt6')
examples = []
for main in examplesMainSources :
	executable = 'examples/'+os.path.splitext(os.path.basename(main))[0]
	examples += [ env.Program(target=executable, source = exampleSources + [main] ) ]

env.Alias('examples',examples)

env.Default(staticLibrary)



