PROGRAMS = \
	SegmentTest \
	TestMIDIIO \
	TestAudioIO \
	TestControlMapper \
	AudioPlayer \
	TestPOComposite \
	TestAudioFileIO \
	TestSnapshots \

TESTS = \
	AllUnitTests \
	TestComplex \
	TestPoint \
	TestPolar \
	TestXMLAdapters \
	TestConfig \
	TestFlags \
	TestSignalv1 \
	TestArray \
	TestArray2 \
	TestDynamicType3 \
	TestError \
	TestFDFilterGen \
	TestFFT \
	TestIFFT \
	TestSpectrum \
	TestSpectrumAdder \
	TestWindowing \
	PhantomBufferTest \
	TestStreamRegions \
	TestStreamBuffer \
	TestEnvelopeExtractor \
	TestWaveGenerator \
	TestSpectrumAdder2 \
	TestSpectrumProduct \
	BPFTest \
	ListTest \

TOP=..

INCLUDE_DIRS+=$(CLAM_PATH)/test/testingWithCppUnit

CLEANFILES=*.data

include $(TOP)/unix_tools/make.rules
