PROGRAMS = \
           TestSnapshots \
           BPFTest \
           ListTest \
           TestMIDIIO \
           TestAudioIO \
           TestControlMapper \
           AudioPlayer \
           TestPOComposite \
           SegmentTest \
           TestAudioFileIO \

TESTS = \
	AllUnitTests \
        TestComplex \
        TestPoint \
        TestPolar \
        TestXMLAdapters \
        TestConfig \
        TestFlags \
        TestArray \
        TestArray2 \
        TestDynamicType3 \
        TestError \
        TestFDFilterGen \
        TestFFT \
        TestIFFT \
        TestSpectrum \
        TestSpectrumAdder \
        TestWindowing \
        PhantomBufferTest \
        TestStreamRegions \
        TestStreamBuffer \
        TestEnvelopeExtractor \
        TestWaveGenerator \
        TestSignalv1 \
        TestSpectrumAdder2 \
        TestSpectrumProduct \

TOP=..

CLEANFILES=*.data

include $(TOP)/unix_tools/make.rules
