// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef SMSTransformPanel_hxx
#define SMSTransformPanel_hxx
#include <FL/Fl.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Tabs.H>

class SMS_ScoreEditor : Fl_Window {
public:
  SMS_ScoreEditor();
private:
  Fl_Window *mMainWindow;
  Fl_Group *mChainTopologyDock;
  Fl_Browser *mRepositoryBox;
  Fl_Browser *mScoreContentsBox;
  Fl_Button *mMoveTransUpInScoreButton;
  Fl_Button *mMoveTransDownInScoreButton;
  Fl_Button *mRemoveTransFromScoreButton;
  Fl_Button *mAddTransformToScoreButton;
  Fl_Group *mTransParmDock;
  Fl_Button *mApplyChangesToCurrentCfg;
  Fl_Button *mDiscardConfigButton;
  Fl_Tabs *mTransTabs;
  Fl_Button *mApplyChangesToScoreButton;
  Fl_Button *mDiscardChangesButton;
};
#endif
