// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "SMSTransformPanel.hxx"

SMS_ScoreEditor::SMS_ScoreEditor() {
  Fl_Window* w;
  { Fl_Window* o = mMainWindow = new Fl_Window(927, 483, "SMS - Transformation Score Edition");
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(49);
    o->selection_color(49);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(56);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { Fl_Group* o = mChainTopologyDock = new Fl_Group(5, 15, 495, 425, "Transformation Score");
      o->box(FL_THIN_UP_FRAME);
      o->color(49);
      o->selection_color(49);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(56);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      { Fl_Browser* o = mRepositoryBox = new Fl_Browser(250, 35, 240, 365, "Available SMS Transformations");
        o->labelsize(12);
        o->textsize(10);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Browser* o = mScoreContentsBox = new Fl_Browser(20, 35, 225, 365, "Transformations in the Score");
        o->labelsize(12);
        o->textsize(10);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Button* o = mMoveTransUpInScoreButton = new Fl_Button(20, 405, 70, 25, "Move &up");
        o->tooltip("Move selected transformations up in the score");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->shortcut(0x80075);
      }
      { Fl_Button* o = mMoveTransDownInScoreButton = new Fl_Button(95, 405, 80, 25, "Move &down");
        o->tooltip("Move selected transformations down in the score");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->shortcut(0x80064);
      }
      { Fl_Button* o = mRemoveTransFromScoreButton = new Fl_Button(180, 405, 65, 25, "&Remove");
        o->tooltip("Remove Transformations from Score");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->shortcut(0x80072);
      }
      { Fl_Button* o = mAddTransformToScoreButton = new Fl_Button(250, 405, 240, 25, "Add &transformation to score");
        o->tooltip("Adds transformation to current score");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->shortcut(0x80074);
      }
      o->end();
    }
    { Fl_Group* o = mTransParmDock = new Fl_Group(505, 15, 420, 465, "Transformation Parameters");
      o->box(FL_NO_BOX);
      o->color(49);
      o->selection_color(49);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(56);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      { Fl_Button* o = mApplyChangesToCurrentCfg = new Fl_Button(620, 445, 150, 30, "Apply configuration");
        o->tooltip("Applies configuration to the selected transformation");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->deactivate();
      }
      { Fl_Button* o = mDiscardConfigButton = new Fl_Button(775, 445, 145, 30, "Discard configuration");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->deactivate();
      }
      { Fl_Tabs* o = mTransTabs = new Fl_Tabs(515, 20, 400, 420);
        o->box(FL_PLASTIC_UP_BOX);
        o->labelsize(12);
        o->end();
      }
      o->end();
    }
    { Fl_Button* o = mApplyChangesToScoreButton = new Fl_Button(5, 450, 230, 25, "&Apply Changes to Score");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->shortcut(0x80061);
    }
    { Fl_Button* o = mDiscardChangesButton = new Fl_Button(250, 450, 250, 25, "&Discard Changes to Score");
      o->box(FL_PLASTIC_UP_BOX);
      o->down_box(FL_PLASTIC_DOWN_BOX);
      o->shortcut(0x80064);
    }
    o->set_modal();
    o->end();
  }
}
