import glob
import os
import sys

moduleName = 'continuous_excitation_synth'
libraryName='plugins_'+moduleName
version = "1.4.0"
description = "Oboe Synthesizer"
url = 'http://clam-project.org'
clamDependencies = [
	'clam_core',
	'clam_audioio',
	'clam_processing',
]
otherDependencies = [
	'fftw3'
]

options = Variables('options.cache', ARGUMENTS)
options.Add(PathVariable('clam_prefix', 'The prefix where CLAM was installed', ''))
options.Add(BoolVariable('verbose', 'Display the full command line instead a short command description', 'yes') )
options.Add(PathVariable('prefix', 'Installation prefix (normally /usr, by default this is clam_prefix)', "", validator=PathVariable.PathAccept))
options.Add(PathVariable('prefix_for_packaging', 'Install location when packaging. Use "." for same as prefix.', '.'))
options.Add(BoolVariable('crossmingw', 'Using MinGW crosscompiler mode', 'no') )


env = Environment(ENV=os.environ, options=options)
options.Save('options.cache', env)
Help(options.GenerateHelpText(env))
env.SConsignFile() # Single signature file

CLAMInstallDir = env['clam_prefix']
InstallDir = env['prefix'] or env['clam_prefix']

clam_sconstoolspath = os.path.join(CLAMInstallDir,'share','clam','sconstools')
if not os.access(os.path.join(clam_sconstoolspath,"clam.py"),os.R_OK):
	raise Exception("CLAM not installed at '%s'. Use clam_prefix option."%CLAMInstallDir)
if env['crossmingw'] :
	env.Tool('crossmingw', toolpath=[clam_sconstoolspath])
env.Tool('clam', toolpath=[clam_sconstoolspath])
env.EnableClamModules(clamDependencies, CLAMInstallDir)


mainSources = {
	'SimpleOboeSynthesizer': './SimpleOboeSynthesizer.cxx',
}
sources = [
	source for source in env.scanFiles('*.cxx', ['.'])
	if source not in mainSources.values()
]
headers = env.scanFiles('*.hxx', ['.'])

env.Append( CCFLAGS=['-g','-O3','-Wall'] )

print(f"{mainSources=}\n{sources=}")

programs = [
	env.Program(target=program, source = [mainSource] + sources)
	for program, mainSource in mainSources.items()
]
libraries = [
	env.SharedLibrary(target=libraryName, source = sources)
]


install, default = env.ClamModule(
	moduleName,
	version,
	description = description,
	url = url,
	sources = sources,
	headers = headers,
	clamDependencies = clamDependencies,
	otherDependencies = otherDependencies,
	)


examples = [
	'synth_with_osc.clamnetwork',
	'synth_with_sliders.clamnetwork',
	]

install += [
	env.Install(os.path.join(InstallDir,'lib','clam'), libraries),
	env.Install(os.path.join(InstallDir,'bin'), programs),
	env.Install(os.path.join(InstallDir,'share','networkeditor','example-data'), examples)
	]
env.Alias('install', install)
env.Default(programs + libraries)

