#!/usr/bin/env python3

def main():
    from qtpy import QtWidgets, QtSvgWidgets
    from ipyclam.qtconsole import ConsoleWidget
    import ipyclam

    app = QtWidgets.QApplication([])
    widget = ConsoleWidget()
    widget.namespace_inject(ipyclam=ipyclam)

    try:
        from ipyclam.clam import Clam_Engine
        widget.namespace_inject(net=ipyclam.Network(Clam_Engine()))
    except ImportError:
        pass

    try:
        from ipyclam.jack import Jack_Engine
        widget.namespace_inject(jack=ipyclam.Network(Jack_Engine()))
    except (ImportError, RuntimeError):
        pass

    widget.namespace_inject(console=widget)
    widget.show()
    app.exec()


if __name__ == '__main__':
    main()
