import os
import sys
import glob

options_filename = 'options.cache'
options = Variables(options_filename, ARGUMENTS)
options.Add(PathVariable('prefix', 'The prefix where the application will be installed', ''))
options.Add(BoolVariable('enable_clam', 'Compile CLAM engine', 'yes'))
options.Add(BoolVariable('enable_jack', 'Compile JACK engine', 'yes'))
if sys.platform=="linux" :
	options.Add(BoolVariable('crossmingw', 'Using MinGW crosscompiler mode', 'no') )

toolchain = 'default'
if sys.platform == 'win32': toolchain = 'mingw'
env = Environment(ENV=os.environ, tools=[toolchain], options=options)
options.Save(options_filename, env)
Help(options.GenerateHelpText(env))

env.SConsignFile() # Single signature file

crosscompiling = env.get("crossmingw")
isWindowsPlatform = sys.platform=='win32' or crosscompiling
isLinuxPlatform = sys.platform=='linux' and not crosscompiling
isDarwinPlatform = sys.platform=='darwin'

env.ParseConfig('python3-config --cflags --embed')
env.ParseConfig('python3-config --libs --embed')
env.ParseConfig('pkg-config --cflags --libs pyside6')

if env['enable_clam'] :
	env.ParseConfig('pkg-config clam_core clam_processing clam_audioio --cflags --libs')
	env.ParseConfig('pkg-config clam_qtmonitors --cflags --libs') # UI binding

env.ParseConfig('pkg-config Qt6UiTools Qt6Gui Qt6Widgets Qt6Core --cflags --libs') # UI binding

if env['enable_jack'] :
	env.ParseConfig('pkg-config --cflags --libs jack')

pyversion = f"{sys.version_info.major}{sys.version_info.minor}" 
env.AppendUnique(LIBS=[f'boost_python{pyversion}'])

# python3-config adds a flag that is refused by g++
if '-Wstrict-prototypes' in env['CCFLAGS'] :
	env['CCFLAGS'].remove('-Wstrict-prototypes')

if True :
	env["SHCXXCOMSTR"] = "Compiling $SOURCE -> $TARGET"
	env["CXXCOMSTR"] = "Compiling $SOURCE -> $TARGET"
	env["SHLINKCOMSTR"] = "Linking $SOURCES -> $TARGET"
	env["LINKCOMSTR"] = "Linking $SOURCES -> $TARGET"

def print_cmd_line(commandline, target, source, env) :
	sys.stdout.write("\033[32;1m%s\033[0m\n"%commandline)
	sys.stdout.flush()
env['PRINT_CMD_LINE_FUNC'] = print_cmd_line


env["SHOBJPREFIX"] = "generated/"


shibokenunwrap = env.SharedObject(source='src/shibokenunwrap.cxx')
sipunwrap = env.SharedObject(source='src/sipunwrap.cxx')

clamengine_module = env.SharedLibrary (
	target='ipyclam/clam',
	source=[
		'src/Clam_Engine.cxx',
		shibokenunwrap,
		sipunwrap,
		],
	SHLIBPREFIX='',
) if env['enable_clam']  else []

clamengine_config_module = env.SharedLibrary (
	target='ipyclam/Clam_ConfigurationProxy',
	source=[
		'src/Clam_ConfigurationProxy.cxx',
		'src/ConfigurationProxy.cxx',
		],
	SHLIBPREFIX='',
) if env['enable_clam']  else []

jackengine_module = env.SharedLibrary (
	target='ipyclam/jack',
	source=[
		'src/Jack_Engine.cxx',
		],
	SHLIBPREFIX='',
) if env['enable_jack']  else []

dummyProcessingsModule = env.SharedLibrary (
	target='ipyclam/dummy/processing',
	source=[
		'src/DummyProcessings.cxx',
		],
	SHLIBPREFIX='',
) if env['enable_clam']  else []

ui_pyside_module = env.SharedLibrary (
	target='ipyclam/ui/PySide',
	source=[
		'src/PySideModule.cxx',
		shibokenunwrap,
		],
	SHLIBPREFIX='',
)
"""
ui_pyqt4_module = env.SharedLibrary (
	target='ipyclam/ui/PyQt4',
	source=[
		'PyQt4Module.cxx',
		sipunwrap,
		],
	SHLIBPREFIX='',
)
"""
program = env.Program(
	target='ipyclam_console',
	source='src/ipyclam_console.cxx',
)
blacklist = [
	"ipyclam/ProxyAPI.py",
]

python_modules = [
	source for source in  glob.glob('ipyclam/*.py')
	if source not in blacklist
	and "Test" not in source
	]

dummy_modules = glob.glob('ipyclam/dummy/*.py')

# TODO: Use distutils to get the paths given a prefix or a home schema
mod_dir = os.path.join(env['prefix'], 'lib', 'python', 'ipyclam')
lib_dir = os.path.join(env['prefix'], 'lib', 'python', 'ipyclam')
dummy_lib_dir = os.path.join(lib_dir, 'dummy')
uilib_dir = os.path.join(lib_dir, 'ui')
bin_dir = os.path.join(env['prefix'], 'bin')

install = [
	env.Install(targetDir, files) for targetDir, files in [
	( lib_dir,[
		clamengine_module,
		clamengine_config_module,
		jackengine_module,
		python_modules,
	]),
	( dummy_lib_dir,[
		dummyProcessingsModule,
		dummy_modules,
	]),
	( uilib_dir, [
		ui_pyside_module,
		#ui_pyqt4_module,
		'ipyclam/ui/__init__.py',
	]),
	( bin_dir,[
		program,
		"ipyclam_console",
		"ipyclam_qtconsole",
	]),
]]

env.Alias('install', install)

Default(
	jackengine_module,
	clamengine_module,
	clamengine_config_module,
	dummyProcessingsModule,
	ui_pyside_module,
	#ui_pyqt4_module,
	program,
)

