.TH networkeditor 9 "August 23, 2005" "version 0.1.2" "X11"
.SH NAME
networkeditor \- digital signal processing systems prototyping application
.SH SYNOPSIS
.B NetworkEditor
.SH DESCRIPTION
The CLAM Network Editor is a digital signal processing (DSP) system prototyping tool. 
It offers a Graphical User Interface so that users can design their systems by combining
'boxes' - that represent digital signal processing objects - and connecting them in 
order to specify the system data flow.
.SH EXIT STATUS
.SH AUTHOR
CLAM development team ( clam (at) iua.upf.es )
