// generated by Fast Light User Interface Designer (fluid) version 1.0103

#include "UserInterface.hxx"
#include <FL/fl_file_chooser.H>
#include "SMSAnalysisSynthesisConfig.hxx"
#include "Fl_SMS_Arrow.hxx"
#include "Fl_SMS_Group.hxx"
#include <FL/fl_message.H>
class Fl_SMS_Group;

inline void SMSBrowser::cb_mCounter_i(Fl_Counter*, void*) {
  //FrameClick();
mNewPosition.Emit( );
}
void SMSBrowser::cb_mCounter(Fl_Counter* o, void* v) {
  ((SMSBrowser*)(o->parent()->user_data()))->cb_mCounter_i(o,v);
}

SMSBrowser::SMSBrowser() {
  Fl_Window* w;
  { Fl_Window* o = mWindow = new Fl_Window(870, 545, "SMSBrowser | MTG-UPF (Barcelona)");
    w = o;
    o->user_data((void*)(this));
    { Fl_Counter* o = mCounter = new Fl_Counter(330, 525, 190, 20, "Frame ");
      o->box(FL_THIN_UP_BOX);
      o->labelsize(12);
      o->minimum(0);
      o->maximum(0);
      o->step(1);
      o->callback((Fl_Callback*)cb_mCounter);
      o->align(FL_ALIGN_LEFT);
      o->deactivate();
    }
    { Fl_Smart_Tile* o = mSmartTile = new Fl_Smart_Tile(5, 5, 860, 515);
      o->box(FL_NO_BOX);
      o->color(49);
      o->selection_color(49);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(56);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    o->end();
    o->resizable(o);
  }
}

short SMSBrowser::h() {
  return mSmartTile->h();
}

short SMSBrowser::w() {
  return mSmartTile->w();
}

void SMSBrowser::show() {
  mWindow->show();
}

void SMSBrowser::redraw() {
  mSmartTile->redraw();
}

void SMSBrowser::add( Fl_Widget* widget ) {
  mSmartTile->add(widget);
}

void SMSBrowser::add( Fl_Widget& widget ) {
  mSmartTile->add(widget);
}

void SMSBrowser::remove( Fl_Widget* widget ) {
  mSmartTile->remove(widget);
}

inline void UserInterface::cb_Open_i(Fl_Button*, void*) {
  LoadConfiguration();
}
void UserInterface::cb_Open(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Open_i(o,v);
}

inline void UserInterface::cb_Edit_i(Fl_Button*, void*) {
  EditConfiguration();
}
void UserInterface::cb_Edit(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Edit_i(o,v);
}

inline void UserInterface::cb_Save_i(Fl_Button*, void*) {
  StoreConfiguration();
}
void UserInterface::cb_Save(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Save_i(o,v);
}

inline void UserInterface::cb_Show_i(Fl_Menu_*, void*) {
  DisplaySpectrumAndPeaks();
}
void UserInterface::cb_Show(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Show_i(o,v);
}

inline void UserInterface::cb_Show1_i(Fl_Menu_*, void*) {
  DisplaySinusoidalTracks();
}
void UserInterface::cb_Show1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Show1_i(o,v);
}

inline void UserInterface::cb_Show2_i(Fl_Menu_*, void*) {
  DisplayResidualSpectrum();
}
void UserInterface::cb_Show2(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Show2_i(o,v);
}

Fl_Menu_Item UserInterface::menu_mSegmentButton[] = {
 {"Show spectrum with peaks", 0,  (Fl_Callback*)UserInterface::cb_Show, 0, 0, 0, 0, 14, 56},
 {"Show sinusoidal tracks", 0,  (Fl_Callback*)UserInterface::cb_Show1, 0, 0, 0, 0, 14, 56},
 {"Show residual spectrum", 0,  (Fl_Callback*)UserInterface::cb_Show2, 0, 0, 0, 0, 14, 56},
 {0}
};

inline void UserInterface::cb_mFirstSegmentButton_i(Fl_File_Button*, void*) {
  mSegmentButton->popup();
}
void UserInterface::cb_mFirstSegmentButton(Fl_File_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mFirstSegmentButton_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_minidata[] = {
"23 25 198 2",
"  \tc None",
". \tc #4F4F4F",
"+ \tc #838383",
"@ \tc #848484",
"# \tc #878787",
"$ \tc #818181",
"% \tc #858585",
"& \tc #E4E4E4",
"* \tc #FFFFFF",
"= \tc #FEFEFE",
"- \tc #FDFDFD",
"; \tc #EFEFEF",
"> \tc #BEBEBE",
", \tc #EDEDED",
"\' \tc #F9F9F9",
") \tc #FCFCFC",
"! \tc #F5F5F5",
"~ \tc #FBFBFB",
"{ \tc #FAFAFA",
"] \tc #F6F6F6",
"^ \tc #E0E0E0",
"/ \tc #B1B1B1",
"( \tc #F0F0F0",
"_ \tc #E8E8E8",
": \tc #A8A8A8",
"< \tc #9D9D9D",
"[ \tc #BDBDBD",
"} \tc #A4A4A4",
"| \tc #BABABA",
"1 \tc #CBCBCB",
"2 \tc #DCDCDC",
"3 \tc #F8F8F8",
"4 \tc #FBFBFA",
"5 \tc #CCCCCC",
"6 \tc #CACACA",
"7 \tc #939392",
"8 \tc #E7E7E7",
"9 \tc #C7C7C7",
"0 \tc #D9D9D9",
"a \tc #E1E1E1",
"b \tc #EAEAEA",
"c \tc #E9E9E9",
"d \tc #EBEBEB",
"e \tc #D6D6D6",
"f \tc #ECECEC",
"g \tc #CDCDCD",
"h \tc #F1F1F1",
"i \tc #D4D4D4",
"j \tc #999999",
"k \tc #7D7D7D",
"l \tc #737373",
"m \tc #111111",
"n \tc #FDFDFC",
"o \tc #F8F8F7",
"p \tc #F5F5F4",
"q \tc #DADADA",
"r \tc #C7C7C6",
"s \tc #171717",
"t \tc #B8B8B8",
"u \tc #B9B9B9",
"v \tc #A1A1A1",
"w \tc #ACACAC",
"x \tc #BCBCBB",
"y \tc #D1D1D1",
"z \tc #BCBCBC",
"A \tc #F6F6F5",
"B \tc #F4F4F4",
"C \tc #1B1B1B",
"D \tc #E9E9E8",
"E \tc #B5B5B5",
"F \tc #DBDBDA",
"G \tc #DADAD9",
"H \tc #D8D8D8",
"I \tc #C5C5C5",
"J \tc #CCCCCB",
"K \tc #D2D2D2",
"L \tc #C9C9C8",
"M \tc #CACAC9",
"N \tc #F2F2F1",
"O \tc #E5E5E4",
"P \tc #E4E4E3",
"Q \tc #D4D4D3",
"R \tc #D7D7D7",
"S \tc #CECECE",
"T \tc #B6B6B6",
"U \tc #DEDEDE",
"V \tc #B4B4B3",
"W \tc #CFCFCE",
"X \tc #C1C1C1",
"Y \tc #F2F2F0",
"Z \tc #DFDFDE",
"` \tc #EEEEEE",
" .\tc #BBBBBB",
"..\tc #D9D9D8",
"+.\tc #9E9E9D",
"@.\tc #A8A8A7",
"#.\tc #B7B7B6",
"$.\tc #D1D1D0",
"%.\tc #F0F0EF",
"&.\tc #EFEFEE",
"*.\tc #EEEEED",
"=.\tc #E6E6E5",
"-.\tc #C4C4C3",
";.\tc #D3D3D2",
">.\tc #D5D5D4",
",.\tc #B3B3B3",
"\'.\tc #C6C6C5",
").\tc #DCDCDB",
"!.\tc #BFBFBE",
"~.\tc #B5B5B4",
"{.\tc #D0D0CF",
"].\tc #CDCDCC",
"^.\tc #EDEDEC",
"/.\tc #EDEDEB",
"(.\tc #E3E3E2",
"_.\tc #DDDDDD",
":.\tc #F7F7F6",
"<.\tc #F4F4F3",
"[.\tc #F3F3F3",
"}.\tc #F2F2F2",
"|.\tc #F1F1F0",
"1.\tc #EFEFED",
"2.\tc #ECECEA",
"3.\tc #EBEBEA",
"4.\tc #D7D7D6",
"5.\tc #EAEAE9",
"6.\tc #F7F7F7",
"7.\tc #C2C2C1",
"8.\tc #CECECD",
"9.\tc #B1B1B0",
"0.\tc #D8D8D7",
"a.\tc #AEAEAD",
"b.\tc #BCBCBA",
"c.\tc #EAEAE8",
"d.\tc #E2E2E1",
"e.\tc #E7E7E6",
"f.\tc #C3C3C3",
"g.\tc #BDBDBC",
"h.\tc #C3C3C2",
"i.\tc #B2B2B1",
"j.\tc #C0C0BF",
"k.\tc #C1C1C0",
"l.\tc #DEDEDD",
"m.\tc #E8E8E7",
"n.\tc #E1E1E0",
"o.\tc #BEBEBD",
"p.\tc #ADADAD",
"q.\tc #CBCBCA",
"r.\tc #C0C0BE",
"s.\tc #D6D6D4",
"t.\tc #BABAB8",
"u.\tc #B0B0AF",
"v.\tc #CBCBC9",
"w.\tc #C8C8C7",
"x.\tc #E2E2E2",
"y.\tc #ADADAC",
"z.\tc #B3B3B2",
"A.\tc #979796",
"B.\tc #A1A1A0",
"C.\tc #AFAFAE",
"D.\tc #C3C3C1",
"E.\tc #B0B0AE",
"F.\tc #C9C9C7",
"G.\tc #E6E6E4",
"H.\tc #E5E5E3",
"I.\tc #ECECEB",
"J.\tc #EBEBE9",
"K.\tc #E9E9E7",
"L.\tc #E8E8E6",
"M.\tc #E7E7E5",
"N.\tc #DFDFDD",
"O.\tc #D6D6D5",
"P.\tc #DBDBD9",
"Q.\tc #DCDCDA",
"R.\tc #DDDDDB",
"S.\tc #CDCDCB",
"T.\tc #E4E4E2",
"U.\tc #BABAB9",
"V.\tc #BEBEBC",
"W.\tc #C5C5C3",
"X.\tc #B4B4B2",
"Y.\tc #D3D3D1",
"Z.\tc #C5C5C4",
"`.\tc #D1D1CF",
" +\tc #CACAC8",
".+\tc #E3E3E1",
"++\tc #D7D7D5",
"@+\tc #D2D2D1",
"#+\tc #D5D5D3",
"$+\tc #CECECC",
"%+\tc #E2E2E0",
"&+\tc #D5D5D5",
"*+\tc #E1E1DF",
"=+\tc #D2D2D0",
"-+\tc #6F6F6F",
";+\tc #161616",
">+\tc #191919",
",+\tc #151515",
". + @ @ @ @ @ @ @ @ @ @ @ @ @ @ # $           ",
"% & * * * * * * * * = = = = = = - ; >         ",
"% , * - \' ) ! ~ - { - = ] = = = ) ^ ) /       ",
"% ( * _ : : < > [ > > } | 1 2 3 4 5 6 [ 7     ",
"% 8 * ! 9 0 a b a c d e f g 8 h \' i j k l m   ",
"% b * = = - - - n ) ) ) ~ ~ { \' 3 o p q r s   ",
"% ; = h t 2 > 2 u v ^ w x y z e A p B b q C   ",
"% D - ( E c 5 F > G H I J u K L M _ N O 0 C   ",
"% P ) ; 9 Q H R S R T U V K u W X Y ( Z 0 C   ",
"% f ~ ` E 0  ...E +.q @.#.1 #.$.%.&.*.=...C   ",
"% b { ` -.;.>.,.y \'.).W G !.~.{.].^./.(.H C   ",
"% _.{ :.A p <.[.}.N |.( %.1., ^./.2.3.4.H C   ",
"@ 5.6.c 7.8.y {.9 $.9.0.a.J ,.L b.c.D d.R C   ",
"@ _ ! e.a.Z f.$.E {.W g.h.i.L j.k.l.m.n.4.C   ",
"@ G A e.o.J 8.p.q.r.s.L Q t.u.v.w.e.=.Q R C   ",
"@ x.[.P y.S z.8.y.A.$.B.C.D.E.F.=.G.H.).4.C   ",
"@ O h ^.I.3.3.J.c.K.m.L.e.M.G.O H.H.P N.e C   ",
"@ G h =.O.P.Q.P.O.G J R.q.4.S.>.{.T.T.O.4.C   ",
"@ G %.l.U.V.U.W.~.-.X.j.7.Y.Z.`. +T..+++e C   ",
"@ n.^.(.Q @+S.++J #+s.$+T.T.(.(..+.+%+R.&+C   ",
"@ q ^.M.M.=.O H.P T.T.(..+.+.+.+%+%+*+4.O.C   ",
"@ ;.1.G.H.P T.T.T.T..+.+.+.+%+%+*+*+*+=+4.C   ",
"-+>.;.$.$.$.$.$.`.{.{.{.{.{.W W W W W @+#.;+  ",
"  >+>+>+>+>+>+>+>+>+>+>+>+>+>+>+>+>+>+>+,+    ",
"                                              "
};
static Fl_Pixmap image_minidata(idata_minidata);

inline void UserInterface::cb_mStoreSMSSynthSound_i(Fl_File_Button*, void*) {
  StoreOutputSound();
}
void UserInterface::cb_mStoreSMSSynthSound(Fl_File_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mStoreSMSSynthSound_i(o,v);
}

static const char *idata_minidirectory[] = {
"24 24 278 2",
"  \tc None",
". \tc #000000",
"+ \tc #666760",
"@ \tc #C4C6B4",
"# \tc #C2C4B2",
"$ \tc #C1C3B2",
"% \tc #C0C2B1",
"& \tc #ACAE9D",
"* \tc #272822",
"= \tc #6C6D6A",
"- \tc #989B7F",
"; \tc #95997E",
"> \tc #94987C",
", \tc #92967B",
"\' \tc #91957A",
") \tc #969A85",
"! \tc #7B7C6D",
"~ \tc #141411",
"{ \tc #5E5E5B",
"] \tc #84876F",
"^ \tc #80836C",
"/ \tc #7F826B",
"( \tc #7F826A",
"_ \tc #7E816A",
": \tc #7D8068",
"< \tc #7A7C66",
"[ \tc #7E806E",
"} \tc #8E917E",
"| \tc #959783",
"1 \tc #969783",
"2 \tc #969883",
"3 \tc #969885",
"4 \tc #959782",
"5 \tc #8E907E",
"6 \tc #838675",
"7 \tc #6E7062",
"8 \tc #4F4F4C",
"9 \tc #6D705B",
"0 \tc #696C58",
"a \tc #686B58",
"b \tc #686A57",
"c \tc #686B57",
"d \tc #636653",
"e \tc #48493F",
"f \tc #5E5F59",
"g \tc #5E5E58",
"h \tc #5E5E57",
"i \tc #5E5D58",
"j \tc #5E5D56",
"k \tc #5D5C56",
"l \tc #5C5C55",
"m \tc #5C5C54",
"n \tc #4B4B46",
"o \tc #3F403B",
"p \tc #5F6250",
"q \tc #5C5F4E",
"r \tc #5C5E4E",
"s \tc #5C5E4D",
"t \tc #5B5D4C",
"u \tc #48493D",
"v \tc #C0C0B8",
"w \tc #E3E4D9",
"x \tc #E0E2D6",
"y \tc #DDDED3",
"z \tc #DCDED2",
"A \tc #DBDCD0",
"B \tc #D9DACF",
"C \tc #D8D9CD",
"D \tc #D7D8CC",
"E \tc #D5D6CA",
"F \tc #D4D4C7",
"G \tc #CCCEC0",
"H \tc #ADAEA0",
"I \tc #20201C",
"J \tc #52524B",
"K \tc #5F605A",
"L \tc #5F6059",
"M \tc #9B9D94",
"N \tc #E1E3D6",
"O \tc #C3C6B1",
"P \tc #C1C4B0",
"Q \tc #BDC0AC",
"R \tc #BABEAA",
"S \tc #B9BBA8",
"T \tc #B6B9A6",
"U \tc #B4B7A4",
"V \tc #B1B4A1",
"W \tc #AEB09E",
"X \tc #ABAC9A",
"Y \tc #A7A997",
"Z \tc #909282",
"` \tc #E3E4D7",
" .\tc #E4E4DA",
"..\tc #E3E4D8",
"+.\tc #E2E3D7",
"@.\tc #E1E2D6",
"#.\tc #E0E1D6",
"$.\tc #C3C4B0",
"%.\tc #C0C2AE",
"&.\tc #BEC0AC",
"*.\tc #BCBEAA",
"=.\tc #BABCA9",
"-.\tc #B9BAA8",
";.\tc #B6B8A5",
">.\tc #B4B6A4",
",.\tc #AFB09E",
"\'.\tc #ACAD9B",
").\tc #A8AA98",
"!.\tc #8F9081",
"~.\tc #797A72",
"{.\tc #CBCDB8",
"].\tc #CACBB6",
"^.\tc #C8CAB5",
"/.\tc #C6C8B2",
"(.\tc #C3C5B1",
"_.\tc #C2C3B0",
":.\tc #C0C1AD",
"<.\tc #BABCA8",
"[.\tc #B8BAA6",
"}.\tc #B6B7A4",
"|.\tc #B4B5A3",
"1.\tc #B1B3A0",
"2.\tc #ACAD9C",
"3.\tc #A9AA98",
"4.\tc #A5A695",
"5.\tc #8C8E7E",
"6.\tc #77786F",
"7.\tc #C8CAB4",
"8.\tc #C6C8B3",
"9.\tc #C4C6B2",
"0.\tc #C2C4B0",
"a.\tc #BFC0AC",
"b.\tc #B8BAA7",
"c.\tc #B4B6A3",
"d.\tc #B2B4A1",
"e.\tc #B0B29F",
"f.\tc #ADB09D",
"g.\tc #ABAC9B",
"h.\tc #A1A291",
"i.\tc #888A7B",
"j.\tc #76776E",
"k.\tc #C5C6B1",
"l.\tc #C2C4AF",
"m.\tc #C0C2AD",
"n.\tc #BEC0AB",
"o.\tc #BCBEA9",
"p.\tc #BABCA7",
"q.\tc #B6B8A4",
"r.\tc #B4B6A2",
"s.\tc #B2B3A0",
"t.\tc #B0B19E",
"u.\tc #ADAE9C",
"v.\tc #AAAC99",
"w.\tc #A6A795",
"x.\tc #A3A492",
"y.\tc #A0A190",
"z.\tc #9C9E8C",
"A.\tc #838576",
"B.\tc #72746A",
"C.\tc #BEC0AA",
"D.\tc #BCBEA8",
"E.\tc #B9BBA6",
"F.\tc #B6B9A4",
"G.\tc #B6B6A2",
"H.\tc #B3B4A0",
"I.\tc #B0B39E",
"J.\tc #AEB09D",
"K.\tc #ACAE9A",
"L.\tc #AAAB99",
"M.\tc #A8A996",
"N.\tc #A5A694",
"O.\tc #A2A492",
"P.\tc #A0A290",
"Q.\tc #9EA08E",
"R.\tc #9B9C8B",
"S.\tc #989988",
"T.\tc #959785",
"U.\tc #7F8071",
"V.\tc #717268",
"W.\tc #BABBA5",
"X.\tc #B7BAA4",
"Y.\tc #B4B6A1",
"Z.\tc #B2B49F",
"`.\tc #B0B29E",
" +\tc #AEB09C",
".+\tc #A9AC98",
"++\tc #A7A996",
"@+\tc #A3A491",
"#+\tc #A0A28F",
"$+\tc #9C9E8B",
"%+\tc #9A9C8A",
"&+\tc #979887",
"*+\tc #949584",
"=+\tc #929382",
"-+\tc #7C7E6F",
";+\tc #B4B7A1",
">+\tc #B0B29D",
",+\tc #AEB09B",
"\'+\tc #ACAD99",
")+\tc #AAAB97",
"!+\tc #A7A995",
"~+\tc #A5A793",
"{+\tc #A1A28F",
"]+\tc #9EA08D",
"^+\tc #999A89",
"/+\tc #969886",
"(+\tc #909281",
"_+\tc #8F907E",
":+\tc #7B7C6E",
"<+\tc #707267",
"[+\tc #AFB29B",
"}+\tc #ADB099",
"|+\tc #ABAD98",
"1+\tc #A9AB96",
"2+\tc #A7A894",
"3+\tc #A4A692",
"4+\tc #A2A490",
"5+\tc #9EA08C",
"6+\tc #9A9B89",
"7+\tc #989A87",
"8+\tc #979886",
"9+\tc #959684",
"0+\tc #929482",
"a+\tc #909180",
"b+\tc #8D8E7D",
"c+\tc #8B8C7C",
"d+\tc #797A6C",
"e+\tc #6F7065",
"f+\tc #AAAD96",
"g+\tc #A8AA95",
"h+\tc #A6A893",
"i+\tc #A4A690",
"j+\tc #A0A28E",
"k+\tc #9C9E8A",
"l+\tc #9A9A88",
"m+\tc #989886",
"n+\tc #969784",
"o+\tc #949683",
"p+\tc #909280",
"q+\tc #8E8F7E",
"r+\tc #8B8C7B",
"s+\tc #888A79",
"t+\tc #888979",
"u+\tc #77786A",
"v+\tc #6C6E63",
"w+\tc #A7A993",
"x+\tc #A5A792",
"y+\tc #A4A58F",
"z+\tc #A1A28E",
"A+\tc #9FA08C",
"B+\tc #9C9F8A",
"C+\tc #9A9C89",
"D+\tc #999A86",
"E+\tc #969785",
"F+\tc #949583",
"G+\tc #929481",
"H+\tc #8C8D7D",
"I+\tc #8A8B7A",
"J+\tc #878878",
"K+\tc #868777",
"L+\tc #767869",
"M+\tc #62625A",
"N+\tc #909380",
"O+\tc #8D8E7C",
"P+\tc #8A8B7B",
"Q+\tc #888A78",
"R+\tc #868876",
"S+\tc #848675",
"T+\tc #828372",
"U+\tc #808171",
"V+\tc #7E7F70",
"W+\tc #7C7E6E",
"X+\tc #797A6B",
"Y+\tc #78796A",
"Z+\tc #76786A",
"`+\tc #757768",
" @\tc #767768",
".@\tc #5E6054",
"                                                ",
"                                                ",
"      . . . . . . .                             ",
"    + @ # $ $ $ % & *                           ",
"    = - ; > > , \' ) ! ~ . . . . . . . . . .     ",
"    { ] ^ / ( _ : < [ } | 1 2 3 | 4 4 5 6 7 .   ",
"    8 9 0 a b c d e f g g h g i j j k l m n .   ",
"    o p q r s t u v w x y z A B C D E F G H .   ",
"    I J K K K L M N O P Q R S T U V W X Y Z .   ",
"    K `  ...+.@.#.$.%.&.*.=.-.;.>.V ,.\'.).!..   ",
"    ~.{.].^./.(._.:.&.*.<.[.}.|.1.,.2.3.4.5..   ",
"    6.7.8.9.0.%.a.*.<.b.;.c.d.e.f.g.).4.h.i..   ",
"    j.k.l.m.n.o.p.[.q.r.s.t.u.v.).w.x.y.z.A..   ",
"    B.C.D.E.F.G.H.I.J.K.L.M.N.O.P.Q.R.S.T.U..   ",
"    V.W.X.Y.Z.`. +K..+++N.@+#+Q.$+%+&+*+=+-+.   ",
"    V.;+Z.>+,+\'+)+!+~+x.{+]+$+%+^+/+*+(+_+:+.   ",
"    <+[+}+|+1+2+3+4+#+5+$+6+7+8+9+0+a+b+c+d+.   ",
"    e+f+g+h+i+4+j+5+k+l+m+n+o+0+p+q+r+s+t+u+.   ",
"    v+w+x+y+z+A+B+C+D+E+F+G+p+_+H+I+J+K+t+L+.   ",
"    M+N+5 O+P+Q+R+S+T+U+V+W+! X+Y+Z+`+ @Z+.@.   ",
"      . . . . . . . . . . . . . . . . . . .     ",
"                                                ",
"                                                ",
"                                                "
};
static Fl_Pixmap image_minidirectory(idata_minidirectory);

inline void UserInterface::cb_mStoreSMSSynthSinusoidal_i(Fl_File_Button*, void*) {
  StoreOutputSoundSinusoidal();
}
void UserInterface::cb_mStoreSMSSynthSinusoidal(Fl_File_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mStoreSMSSynthSinusoidal_i(o,v);
}

inline void UserInterface::cb_mStoreSMSSynthResidual_i(Fl_File_Button*, void*) {
  StoreOutputSoundResidual();
}
void UserInterface::cb_mStoreSMSSynthResidual(Fl_File_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mStoreSMSSynthResidual_i(o,v);
}

inline void UserInterface::cb_mSMSTransformationButton_i(Fl_Button*, void*) {
  Transform();
}
void UserInterface::cb_mSMSTransformationButton(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mSMSTransformationButton_i(o,v);
}

inline void UserInterface::cb_mStoreAnalysis_i(Fl_Button*, void*) {
  StoreAnalysisData();
}
void UserInterface::cb_mStoreAnalysis(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mStoreAnalysis_i(o,v);
}

inline void UserInterface::cb_mSMSSynthesisButton_i(Fl_Button*, void*) {
  Synthesize( );
}
void UserInterface::cb_mSMSSynthesisButton(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mSMSSynthesisButton_i(o,v);
}

inline void UserInterface::cb_mStoreTransformation_i(Fl_Button*, void*) {
  StoreTransformationData();
}
void UserInterface::cb_mStoreTransformation(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mStoreTransformation_i(o,v);
}

inline void UserInterface::cb_mSMSAnalysisButton_i(Fl_Button*, void*) {
  Analyze();
}
void UserInterface::cb_mSMSAnalysisButton(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mSMSAnalysisButton_i(o,v);
}

inline void UserInterface::cb_Open1_i(Fl_Button*, void*) {
  LoadAnalysisData( );
}
void UserInterface::cb_Open1(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_Open1_i(o,v);
}

inline void UserInterface::cb_mAudioInButton_i(Fl_Display_Button*, void*) {
  DisplayInputSound( );
}
void UserInterface::cb_mAudioInButton(Fl_Display_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mAudioInButton_i(o,v);
}

inline void UserInterface::cb_mShowSynthesizedAudio_i(Fl_Display_Button*, void*) {
  DisplaySynthesizedAudio();
}
void UserInterface::cb_mShowSynthesizedAudio(Fl_Display_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mShowSynthesizedAudio_i(o,v);
}

inline void UserInterface::cb_mShowSynthesizedSinusoidal_i(Fl_Display_Button*, void*) {
  DisplaySynthesizedSinusoidal();
}
void UserInterface::cb_mShowSynthesizedSinusoidal(Fl_Display_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mShowSynthesizedSinusoidal_i(o,v);
}

inline void UserInterface::cb_mShowSynthesizedResidual_i(Fl_Display_Button*, void*) {
  DisplaySynthesizedResidual();
}
void UserInterface::cb_mShowSynthesizedResidual(Fl_Display_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mShowSynthesizedResidual_i(o,v);
}

inline void UserInterface::cb_mExtractMelody_i(Fl_Button*, void*) {
  AnalyzeMelody();
}
void UserInterface::cb_mExtractMelody(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mExtractMelody_i(o,v);
}

inline void UserInterface::cb_mStoreMelodyButton_i(Fl_File_Button*, void*) {
  StoreMelody();
}
void UserInterface::cb_mStoreMelodyButton(Fl_File_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mStoreMelodyButton_i(o,v);
}

inline void UserInterface::cb__i(Fl_File_Button*, void*) {
  LoadSelectedSound();
}
void UserInterface::cb_(Fl_File_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb__i(o,v);
}

static const char *idata_mtg[] = {
"72 49 234 2",
"  \tc None",
". \tc #FCDFDF",
"+ \tc #EF5E60",
"@ \tc #EB3234",
"# \tc #F06567",
"$ \tc #E81A1C",
"% \tc #F27F81",
"& \tc #F17273",
"* \tc #7A749F",
"= \tc #665E90",
"- \tc #76709C",
"; \tc #756F9C",
"> \tc #746C9A",
", \tc #5D5D92",
"\' \tc #FFA4A2",
") \tc #F5A1A2",
"! \tc #F49091",
"~ \tc #F38687",
"{ \tc #FBD9DA",
"] \tc #F9C3C3",
"^ \tc #F17678",
"/ \tc #F17374",
"( \tc #F8B5B6",
"_ \tc #F7ADAE",
": \tc #EC4547",
"< \tc #F6A3A4",
"[ \tc #F6A8A9",
"} \tc #F38788",
"| \tc #FBD2D3",
"1 \tc #F7B4B4",
"2 \tc #F17475",
"3 \tc #F06E6F",
"4 \tc #ED4A4C",
"5 \tc #706998",
"6 \tc #585186",
"7 \tc #686292",
"8 \tc #666091",
"9 \tc #676192",
"0 \tc #4E4D88",
"a \tc #FF1C13",
"b \tc #E61A1D",
"c \tc #EB3839",
"d \tc #F6A7A8",
"e \tc #F06A6B",
"f \tc #ED4849",
"g \tc #FF3932",
"h \tc #F38889",
"i \tc #F8BABA",
"j \tc #F06B6C",
"k \tc #EC4345",
"l \tc #F59FA0",
"m \tc #EA2C2E",
"n \tc #F3898A",
"o \tc #F38B8C",
"p \tc #F17071",
"q \tc #F27C7D",
"r \tc #FBD7D8",
"s \tc #F59798",
"t \tc #A39FBC",
"u \tc #9590B3",
"v \tc #A19DBB",
"w \tc #A09CBA",
"x \tc #9E99B9",
"y \tc #8D8DB2",
"z \tc #FF3C34",
"A \tc #F49596",
"B \tc #E92022",
"C \tc #F38384",
"D \tc #F48F90",
"E \tc #4F4780",
"F \tc #5F588C",
"G \tc #5E568A",
"H \tc #484784",
"I \tc #F17879",
"J \tc #E92728",
"K \tc #EB3C3E",
"L \tc #EA292B",
"M \tc #E92325",
"N \tc #ED4D4F",
"O \tc #EC3D3F",
"P \tc #B1AEC7",
"Q \tc #A8A4C0",
"R \tc #B2AFC8",
"S \tc #B2AEC7",
"T \tc #A1A1C0",
"U \tc #EE5759",
"V \tc #443C78",
"W \tc #534C83",
"X \tc #524B82",
"Y \tc #524881",
"Z \tc #39387A",
"` \tc #FF3B33",
" .\tc #F27B7C",
"..\tc #F8B7B8",
"+.\tc #ED4F51",
"@.\tc #EA2B2D",
"#.\tc #EF6364",
"$.\tc #AFABC5",
"%.\tc #B0ADC6",
"&.\tc #B0ABC5",
"*.\tc #9F9FBF",
"=.\tc #EA2F30",
"-.\tc #251B62",
";.\tc #393070",
">.\tc #372E6F",
",.\tc #382F6F",
"\'.\tc #372B6D",
").\tc #1B1A66",
"!.\tc #FF3831",
"~.\tc #F8BDBD",
"{.\tc #E71B1D",
"].\tc #F59A9A",
"^.\tc #D5D3E0",
"/.\tc #CDCCDC",
"(.\tc #D7D6E2",
"_.\tc #D6D5E2",
":.\tc #D5D4E1",
"<.\tc #D6D4E1",
"[.\tc #FF2016",
"}.\tc #E41C1F",
"|.\tc #F35152",
"1.\tc #E61C1E",
"2.\tc #E61D1F",
"3.\tc #E71D1F",
"4.\tc #F44A4B",
"5.\tc #E71C1E",
"6.\tc #36366A",
"7.\tc #12124E",
"8.\tc #27275E",
"9.\tc #262661",
"0.\tc #32316F",
"a.\tc #2A2A67",
"b.\tc #272767",
"c.\tc #14145C",
"d.\tc #FF6C6C",
"e.\tc #FF1D1D",
"f.\tc #FF9595",
"g.\tc #FF3030",
"h.\tc #FF2F2F",
"i.\tc #FF5D5D",
"j.\tc #FE1515",
"k.\tc #F31214",
"l.\tc #FD0A0A",
"m.\tc #FFB5B5",
"n.\tc #EE5557",
"o.\tc #F28283",
"p.\tc #F9FBFB",
"q.\tc #F6F9F9",
"r.\tc #F1F1EC",
"s.\tc #EEEDEA",
"t.\tc #F8F8F6",
"u.\tc #FEFDFD",
"v.\tc #F6F6F3",
"w.\tc #E2E2DD",
"x.\tc #FCFCFC",
"y.\tc #E7E8D9",
"z.\tc #EBEDED",
"A.\tc #EDF4F4",
"B.\tc #DAE5E4",
"C.\tc #B6B6B6",
"D.\tc #EDEDED",
"E.\tc #E1E7E7",
"F.\tc #FCFBFB",
"G.\tc #E7F2F2",
"H.\tc #DFDFDE",
"I.\tc #E6E5E5",
"J.\tc #E6EDED",
"K.\tc #E2EEEE",
"L.\tc #FBFCFC",
"M.\tc #E8E8E8",
"N.\tc #EBEAEA",
"O.\tc #F0F0F0",
"P.\tc #EAF0F0",
"Q.\tc #FCC6C7",
"R.\tc #F6A6A7",
"S.\tc #BAB9B9",
"T.\tc #A4A2A3",
"U.\tc #C3C1C3",
"V.\tc #C0BEBF",
"W.\tc #C9C8C8",
"X.\tc #A8A6A8",
"Y.\tc #DADADA",
"Z.\tc #CCCBCC",
"`.\tc #C8C7C7",
" +\tc #CAC8C5",
".+\tc #ACABAB",
"++\tc #BCC2C2",
"@+\tc #C7C5C5",
"#+\tc #E3E2E2",
"$+\tc #B1AEAE",
"%+\tc #C5C4C4",
"&+\tc #C1C6C6",
"*+\tc #C8CDCD",
"=+\tc #C5C0C0",
"-+\tc #CCC9C9",
";+\tc #E1E0E0",
">+\tc #CDCCCC",
",+\tc #C3C1C1",
"\'+\tc #BDB9B9",
")+\tc #B6B0B0",
"!+\tc #CDCFCF",
"~+\tc #C6CBCB",
"{+\tc #F3F3F3",
"]+\tc #AFADAD",
"^+\tc #BFBDBD",
"/+\tc #CBC9C9",
"(+\tc #C2C3C3",
"_+\tc #BABEBD",
":+\tc #E3EAEA",
"<+\tc #F3080A",
"[+\tc #DDDDDD",
"}+\tc #D6D5D5",
"|+\tc #B4B3B3",
"1+\tc #D0CFCF",
"2+\tc #CBCACA",
"3+\tc #A8A7A7",
"4+\tc #D2D1D1",
"5+\tc #B1AFB0",
"6+\tc #CCCBCB",
"7+\tc #B3B1B1",
"8+\tc #AAA9A9",
"9+\tc #9D9B9B",
"0+\tc #B8B7B7",
"a+\tc #CED1D0",
"b+\tc #FEF6F6",
"c+\tc #F41F21",
"d+\tc #D4D3D3",
"e+\tc #CECDCD",
"f+\tc #F9F9F9",
"g+\tc #EEEDED",
"h+\tc #EFEEEE",
"i+\tc #FAF9F9",
"j+\tc #EC4041",
"k+\tc #EF5C5D",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
             . + @                                                 ",
"                                                                             \
             # $ $                                                 ",
"                                                                             \
             % $ $                                 &               ",
"          * = - ; ; ; ; ; ; ; ; ; - > ,     \' )     ! # # ~ {     ] ^ + / ( \
          & _ : $ $ < [ } |             1 2 + 3 ( & $ 4 &           ",
"          5 6 7 8 8 8 8 8 8 8 8 8 9 = 0     a b [ c $ $ $ $ $ d ^ $ $ $ $ $ e\
         & $ $ $ $ $ $ $ e         & f $ $ $ $ $ $ $ @ &           ",
"                                            g b $ $ h i j $ $ $ $ k 1 l m $ $\
 )       & $ $ $ $ n o p ]         k $ $ q r s $ $ $ &             ",
"          t u v w w w w w w w w w w x y     z b $ &       A $ $ p       & B $\
 :           C $ $               ] $ $ A       ] $ $ D             ",
"          7 E F F F F F F F F F F F G H     z b I         & $ $ &         e $\
 m           2 $ J               C $ $           K $ k             ",
"                                            g b &         & $ $ &         h $\
 L           & $ J               ^ $ M           N $ O             ",
"          P Q R P P P P P P P P P P S T     g b 3         & $ $ &         n $\
 m           & $ J               < $ $ &         B $ U             ",
"          G V W X X X X X X X X X X Y Z     ` b 3         & $ $ &         h $\
 m           & $ J               & $ $ :        .$ $ ..            ",
"                                            g b 3         & $ $ &         h $\
 m           & $ J                 $ $ $ M +.@.$ $ #.              ",
"          $.Q P %.%.%.%.%.%.%.%.%.%.&.*.    ` b 3         & $ $ &         h $\
 m           3 $ =.                  $ $ $ $ $ $ $                 ",
"          V -.;.>.>.>.>.>.,.>.>.>.,.\'.).    ` b 3         & $ $ &         h \
$ m            .$ $                 n $ !                           ",
"                                            !.b 3         & $ $ &         ~ $\
 @.          ~.{.$ +.& & & &     & $ $     ].e +.U [               ",
"          ^./.(._._._._.:.^.^.<._._.<./.    [.}.|.        & 1.2.&         2 3\
.3.            4.2.3.5.3.3.l       L $ $ $ $ $ $ $ $ +             ",
"          6.7.8.9.9.8.8.8.0.a.8.b.b.9.c.    d.e.f.        & g.h.&         \' \
e.i.              d.j.k.l.j.m.      & & 4 n.o.1 1 +.$ $ i           ",
"                                                  p.              q.         \
                                                   M $ <           ",
"          r.s.t.    u.v.v.w.x.r.t.  y.s.  z.  A.B.C.D.  E.u.F.G.z.H.F.I.  J.K\
.  x.L.  M.N.O.z.A.A.      P.E.    Q.A           & $ $ R.          ",
"          S.T.U.V.D.W.X.Y.Z.V.`.O.  V.H. +.+++@+#+$+%+W.S.&+*+=+-+;+>+%+,+\'+\
)+!+~+t.{+]+^+S./+=+(+&+I.-+\'+_+:+  <+{.=.! i ( I $ $ $ &           ",
"          [+`.}+|+1+,+`.`.2+3+I.    4+[+5+`.V.4+{+6+Y.7+I.%+,+}+\'+W.@+}+|+8+\
I.,+|+  {+9+6+1+O.6+4+|+>+0+/+a+B.b+c+{.$ $ $ $ $ $ M |             ",
"          N.[+M.#+%+4+d+}+M.I.V.I.  ;+1+;+e+f+@+e+#+N.}+g+h+Y.@+h+H.}+1+N.T.6\
+>+1+  i+8+C.H.  }+>+h+%+e+]+++p.    & o.j+M m k+R.                ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   ",
"                                                                             \
                                                                   "
};
static Fl_Pixmap image_mtg(idata_mtg);

static const char *idata_iua[] = {
"45 49 153 2",
"  \tc None",
". \tc #F8ACAF",
"+ \tc #F8A7AB",
"@ \tc #F15358",
"# \tc #F79DA0",
"$ \tc #F9AEB0",
"% \tc #FAB9BB",
"& \tc #F69697",
"* \tc #F58489",
"= \tc #F6878B",
"- \tc #F9B7B9",
"; \tc #F37D82",
"> \tc #F15056",
", \tc #F46B72",
"\' \tc #F89EA2",
") \tc #F9BFC2",
"! \tc #F48489",
"~ \tc #F7A0A4",
"{ \tc #EF2A2D",
"] \tc #F69497",
"^ \tc #F16366",
"/ \tc #F79295",
"( \tc #F68A8F",
"_ \tc #F7A7AB",
": \tc #F16263",
"< \tc #EA0000",
"[ \tc #EB0000",
"} \tc #EA0007",
"| \tc #EC0B0F",
"1 \tc #EC050E",
"2 \tc #EC1115",
"3 \tc #EB1619",
"4 \tc #ED2229",
"5 \tc #ED262C",
"6 \tc #EF4D4E",
"7 \tc #F58588",
"8 \tc #EC1619",
"9 \tc #E80000",
"0 \tc #EC2328",
"a \tc #F47778",
"b \tc #F7999D",
"c \tc #F9ABAF",
"d \tc #F79DA1",
"e \tc #F69091",
"f \tc #F68F8F",
"g \tc #F3676C",
"h \tc #F36D71",
"i \tc #F36364",
"j \tc #F15E5E",
"k \tc #EC171E",
"l \tc #F15255",
"m \tc #ED3436",
"n \tc #F36268",
"o \tc #F2666A",
"p \tc #F14B50",
"q \tc #F9B2B4",
"r \tc #F68D90",
"s \tc #F58389",
"t \tc #F1484F",
"u \tc #F3747A",
"v \tc #EA0D0D",
"w \tc #EF3A42",
"x \tc #F16064",
"y \tc #EF343C",
"z \tc #F6888D",
"A \tc #F7979B",
"B \tc #F0474F",
"C \tc #E90A14",
"D \tc #F26165",
"E \tc #F47072",
"F \tc #F79A9D",
"G \tc #F25A5E",
"H \tc #F25F65",
"I \tc #EE212A",
"J \tc #EF363E",
"K \tc #E90002",
"L \tc #EB1A19",
"M \tc #F79EA3",
"N \tc #F8A8AC",
"O \tc #F15A60",
"P \tc #ED282F",
"Q \tc #F37175",
"R \tc #EF363C",
"S \tc #F04F51",
"T \tc #E70707",
"U \tc #EE141C",
"V \tc #E90000",
"W \tc #EF3738",
"X \tc #F78F93",
"Y \tc #EB151C",
"Z \tc #F36C70",
"` \tc #EA0808",
" .\tc #ED2D35",
"..\tc #ED1119",
"+.\tc #F0343C",
"@.\tc #F7A1A2",
"#.\tc #E90001",
"$.\tc #F79398",
"%.\tc #FABCBC",
"&.\tc #E90606",
"*.\tc #F36066",
"=.\tc #FABABC",
"-.\tc #E90303",
";.\tc #F59296",
">.\tc #F9BBBE",
",.\tc #ED2329",
"\'.\tc #E70000",
").\tc #F35C63",
"!.\tc #F47B7F",
"~.\tc #EE3234",
"{.\tc #EA0003",
"].\tc #F15558",
"^.\tc #E70405",
"/.\tc #F57D7E",
"(.\tc #F0484D",
"_.\tc #F9AFB2",
":.\tc #F36B71",
"<.\tc #EF474E",
"[.\tc #ED1A22",
"}.\tc #F15058",
"|.\tc #F6898E",
"1.\tc #F8A4A7",
"2.\tc #F8B0B3",
"3.\tc #ED282B",
"4.\tc #EA0001",
"5.\tc #EC0E16",
"6.\tc #F8A2A5",
"7.\tc #ED252A",
"8.\tc #EF4346",
"9.\tc #E90003",
"0.\tc #EA2C2D",
"a.\tc #F57377",
"b.\tc #EC151C",
"c.\tc #F3696B",
"d.\tc #F56D73",
"e.\tc #EC2426",
"f.\tc #EB0912",
"g.\tc #EE2930",
"h.\tc #EE222A",
"i.\tc #EC3032",
"j.\tc #F58183",
"k.\tc #F37278",
"l.\tc #F5898D",
"m.\tc #F68E91",
"n.\tc #F58689",
"o.\tc #EE3138",
"p.\tc #ED2C33",
"q.\tc #F79A9E",
"r.\tc #F69094",
"s.\tc #EC1E26",
"t.\tc #EB1820",
"u.\tc #EE2F38",
"v.\tc #F14D51",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                    .       +                \
             ",
"                                                          + +                \
             ",
"                                                                             \
             ",
"                                      +             + @   #             $ %  \
             ",
"                                      +             & *   = -           ; >  \
             ",
"                                      ,             + \'   ) +         , , ! \
,             ",
"                                      ,             ~ { ] ^ / , , , , , , , (\
             ",
"                                      +       , _ : < [ } | 1 2 3 4 5 6 7    \
             ",
"                                            ] 8 9 0 a b , c d e f g h 6 < i  \
             ",
"                                          j k l + ,                       m n\
             ",
"                                        o p q +                             r\
             ",
"                                        % +                                  \
             ",
"                                                                             \
             ",
"                  s t u                                                      \
             ",
"              t v w x y k                                                    \
             ",
"              < z       A B                                                  \
             ",
"          , C D           E                             F G H +              \
             ",
"          I J             :                     + G K L M + + N O P Q +      \
             ",
"          R S           e T                 / U k V W               X Y ,    \
             ",
"          Z `        .....+             , +.R + @.#.$.      %.n +     j V    \
             ",
"            &.*.                      ,  .=.    d -.;.    >.,.\'.l +   ).B   \
              ",
"            !.~.                                o {.,     + ].^./.    p +   (\
.n           ",
"              3                         , ,     _.< u       + :.+     <., , [\
.}.          ",
"              } |.                      1.H 2.    V 3.+           + A L 4.y ,\
             ",
"              5.D                           h b 6.V } 7., , , , , 8.9.0.a.+  \
             ",
"              b.c.                            @.O d.R e.f.g.h.< V i.j.+      \
             ",
"              f.k.                                  , , , l.l.m., +          \
             ",
"              5.n.                                                           \
             ",
"              [.,                                                            \
             ",
"              o.6.                                                           \
             ",
"              R g                                                            \
             ",
"              p.t           q.,                                              \
             ",
"              r.K ,       , s.,                                              \
             ",
"                , t.m., !.u.b                                                \
             ",
"                    , v.a.                                                   \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             ",
"                                                                             \
             "
};
static Fl_Pixmap image_iua(idata_iua);

inline void UserInterface::cb_mSMSTransformationLoad_i(Fl_Button*, void*) {
  LoadTransformation();
}
void UserInterface::cb_mSMSTransformationLoad(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mSMSTransformationLoad_i(o,v);
}

inline void UserInterface::cb_mSMSTransformationUndo_i(Fl_Button*, void*) {
  UndoTransform();
}
void UserInterface::cb_mSMSTransformationUndo(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_mSMSTransformationUndo_i(o,v);
}

inline void UserInterface::cb_mCounter1_i(Fl_Counter*, void*) {
  ChangeFrame();
}
void UserInterface::cb_mCounter1(Fl_Counter* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mCounter1_i(o,v);
}

UserInterface::UserInterface() {
  Fl_Window* w;
  { Fl_Window* o = mWindow = new Fl_Window(880, 470, "SMSTools. An analysis/synthesis application | MTG-UPF (Barcelona)");
    w = o;
    o->user_data((void*)(this));
    { Fl_SMS_Group* o = new Fl_SMS_Group(5, 5, 870, 210, "Project Box");
      o->box(FL_BORDER_FRAME);
      o->color(0);
      o->selection_color(49);
      o->labeltype(FL_NO_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(56);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      { Fl_Box* o = new Fl_Box(10, 10, 50, 20, "Project");
        o->labelsize(12);
      }
      { Fl_Button* o = new Fl_Button(60, 10, 70, 20, "Open...");
        o->tooltip("Opens a global configuration file");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Open);
      }
      { Fl_Button* o = new Fl_Button(130, 10, 70, 20, "Edit...");
        o->tooltip("Edits the current configuration");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Edit);
      }
      { Fl_Button* o = new Fl_Button(200, 10, 70, 20, "Save...");
        o->tooltip("Saves the current configuration");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Save);
      }
      { Fl_Group* o = new Fl_Group(245, 90, 70, 85);
        o->color(0);
        { Fl_SMS_Arrow* o = mAnalysisDataFromProcess = new Fl_SMS_Arrow(245, 90, 70, 35, "\\>");
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          o->color(49);
          o->selection_color(49);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(56);
          o->align(FL_ALIGN_CENTER);
          o->when(FL_WHEN_RELEASE);
        }
        { Fl_SMS_Arrow* o = mAnalysisDataFromFile = new Fl_SMS_Arrow(245, 125, 70, 35, "/>");
          o->type(102);
          o->box(FL_THIN_UP_BOX);
          o->color(49);
          o->selection_color(49);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(56);
          o->align(FL_ALIGN_CENTER);
          o->when(FL_WHEN_RELEASE);
        }
        o->end();
      }
      { Fl_Menu_Button* o = mSegmentButton = new Fl_Menu_Button(315, 115, 25, 25);
        o->box(FL_THIN_UP_BOX);
        o->color(48);
        o->hide();
        o->menu(menu_mSegmentButton);
      }
      { Fl_File_Button* o = mFirstSegmentButton = new Fl_File_Button(315, 115, 25, 25);
        o->box(FL_NO_BOX);
        o->color(0);
        o->selection_color(49);
        o->image(image_minidata);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mFirstSegmentButton);
        o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(340, 130, 40, 30, "\\>");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(340, 90, 40, 40, "/>");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(500, 90, 40, 40, "\\>");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_Box* o = mSecondSegmentButton = new Fl_Box(540, 115, 20, 25);
        o->box(FL_NO_BOX);
        o->color(0);
        o->selection_color(49);
        o->image(image_minidata);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(560, 130, 45, 30, "\\>");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(560, 90, 45, 40, "/>");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(340, 125, 200, 10, "->");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_File_Button* o = mStoreSMSSynthSound = new Fl_File_Button(845, 50, 25, 20);
        o->tooltip("Saves the audio to a file");
        o->box(FL_NO_BOX);
        o->color(0);
        o->selection_color(49);
        o->image(image_minidirectory);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mStoreSMSSynthSound);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_File_Button* o = mStoreSMSSynthSinusoidal = new Fl_File_Button(845, 85, 25, 20);
        o->tooltip("Saves the audio to a file");
        o->box(FL_NO_BOX);
        o->color(0);
        o->selection_color(49);
        o->image(image_minidirectory);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mStoreSMSSynthSinusoidal);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_File_Button* o = mStoreSMSSynthResidual = new Fl_File_Button(845, 115, 25, 20);
        o->tooltip("Saves the audio to a file");
        o->box(FL_NO_BOX);
        o->color(0);
        o->selection_color(49);
        o->image(image_minidirectory);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mStoreSMSSynthResidual);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(120, 95, 15, 10, "-");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(705, 95, 40, 35, "\\>");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(705, 60, 40, 35, "/>");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_SMS_Arrow* o = new Fl_SMS_Arrow(705, 90, 40, 10, "->");
        o->box(FL_NO_BOX);
        o->color(49);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_Button* o = mSMSTransformationButton = new Fl_Button(380, 80, 130, 35, "SMS Transformation");
        o->tooltip("Orders the SMSTransformation");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_mSMSTransformationButton);
        o->deactivate();
      }
      { Fl_Button* o = mStoreAnalysis = new Fl_Button(380, 140, 95, 30, "Save to file...");
        o->tooltip("Saves the analyzed data to a file");
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_mStoreAnalysis);
        o->deactivate();
      }
      { Fl_Button* o = mSMSSynthesisButton = new Fl_Button(605, 80, 100, 35, "SMS Synthesis");
        o->tooltip("Orders the SMSSynthesis");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_mSMSSynthesisButton);
        o->deactivate();
      }
      { Fl_Button* o = mStoreTransformation = new Fl_Button(605, 140, 100, 30, "Save to file...");
        o->tooltip("Saves the transformed data to a file");
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_mStoreTransformation);
        o->deactivate();
      }
      { Fl_Button* o = mSMSAnalysisButton = new Fl_Button(135, 80, 110, 35, "SMS Analysis");
        o->tooltip("Orders the SMSAnalysis");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_mSMSAnalysisButton);
        o->deactivate();
      }
      { Fl_Button* o = new Fl_Button(140, 140, 105, 30, "Open from file...");
        o->tooltip("Opens the analyzed data from a file");
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Open1);
      }
      { Fl_Display_Button* o = mAudioInButton = new Fl_Display_Button(40, 80, 85, 35, "Input Audio");
        o->tooltip("Shows the input audio");
        o->box(FL_THIN_UP_BOX);
        o->color(48);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mAudioInButton);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_Display_Button* o = mShowSynthesizedAudio = new Fl_Display_Button(745, 50, 95, 25, "Output Audio");
        o->tooltip("Shows the output audio");
        o->box(FL_THIN_UP_BOX);
        o->color(48);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mShowSynthesizedAudio);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_Display_Button* o = mShowSynthesizedSinusoidal = new Fl_Display_Button(745, 80, 95, 25, "Sinusoidal part");
        o->tooltip("Shows the sinusoidal audio part");
        o->box(FL_THIN_UP_BOX);
        o->color(48);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mShowSynthesizedSinusoidal);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_Display_Button* o = mShowSynthesizedResidual = new Fl_Display_Button(745, 110, 95, 25, "Residual part");
        o->tooltip("Shows the residual audio part");
        o->box(FL_THIN_UP_BOX);
        o->color(48);
        o->selection_color(49);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mShowSynthesizedResidual);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
        o->deactivate();
      }
      { Fl_Button* o = mExtractMelody = new Fl_Button(225, 180, 105, 30, "Extract melody");
        o->tooltip("Calculates the melody of the audio");
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_mExtractMelody);
        o->deactivate();
      }
      { Fl_File_Button* o = mStoreMelodyButton = new Fl_File_Button(330, 180, 25, 20);
        o->tooltip("Saves the melody to a file");
        o->box(FL_NO_BOX);
        o->color(0);
        o->selection_color(49);
        o->image(image_minidirectory);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_mStoreMelodyButton);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_File_Button* o = new Fl_File_Button(10, 80, 25, 20);
        o->tooltip("Opens an audio file");
        o->box(FL_NO_BOX);
        o->color(0);
        o->selection_color(49);
        o->image(image_minidirectory);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(12);
        o->labelcolor(56);
        o->callback((Fl_Callback*)cb_);
        o->align(FL_ALIGN_CENTER);
        o->when(FL_WHEN_RELEASE);
      }
      { Fl_Group* o = new Fl_Group(320, 10, 405, 55, "About box");
        o->labeltype(FL_NO_LABEL);
        { Fl_Box* o = new Fl_Box(380, 15, 70, 40);
          o->image(image_mtg);
        }
        { Fl_Box* o = new Fl_Box(450, 20, 200, 15, "SMS Analysis/Synthesis Application");
          o->labelfont(3);
          o->labelsize(11);
        }
        { Fl_Box* o = new Fl_Box(455, 35, 190, 15, "by MTG - IUA - UPF (Barcelona, Spain)");
          o->labelfont(2);
          o->labelsize(11);
        }
        { Fl_Box* o = new Fl_Box(420, 50, 265, 15, "please visit us at http://www.iua.upf.es/mtg for more info");
          o->labelfont(2);
          o->labelsize(10);
        }
        { Fl_Box* o = new Fl_Box(645, 10, 50, 40);
          o->image(image_iua);
        }
        o->end();
      }
      { Fl_Button* o = mSMSTransformationLoad = new Fl_Button(435, 65, 40, 15, "Open...");
        o->tooltip("Orders the SMSTransformation");
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_mSMSTransformationLoad);
        o->deactivate();
      }
      { Fl_Button* o = mSMSTransformationUndo = new Fl_Button(475, 65, 35, 15, "Undo");
        o->tooltip("Undoes the SMSTransformation");
        o->labelsize(10);
        o->callback((Fl_Callback*)cb_mSMSTransformationUndo);
        o->deactivate();
      }
      o->end();
    }
    { Fl_Smart_Tile* o = mSmartTile = new Fl_Smart_Tile(5, 220, 870, 225);
      o->box(FL_NO_BOX);
      o->color(49);
      o->selection_color(49);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(56);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      o->minsize(80);
      o->end();
      Fl_Group::current()->resizable(o);
    }
    { Fl_Counter* o = mCounter = new Fl_Counter(395, 450, 135, 20, "Frame:");
      o->tooltip("Shows and changes the selected frame number");
      o->box(FL_THIN_UP_BOX);
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_mCounter1);
      o->align(FL_ALIGN_LEFT);
      o->deactivate();
    }
    o->end();
  }
}
