// generated by Fast Light User Interface Designer (fluid) version 1.0103

#ifndef UserInterface_hxx
#define UserInterface_hxx
#include <FL/Fl.H>
#include "Fl_Config_Button.hxx"
#include "Fl_Data_Button.hxx"
#include "Fl_Display_Button.hxx"
#include "Fl_File_Button.hxx"
#include <FL/Fl_Tile.H>
#include "Fl_Smart_Tile.hxx"
#include "ForwardDeclarations.hxx"
class Fl_Smart_Tile;
class Fl_Config_Button;
class Fl_Display_Button;
class Fl_File_Button;
class Fl_SMS_Arrow;
class Fl_Smart_Tile;
#include <FL/Fl_Window.H>
#include <FL/Fl_Counter.H>

class SMSBrowser {
public:
  SMSBrowser();
  Fl_Window *mWindow;
  Fl_Counter *mCounter;
private:
  inline void cb_mCounter_i(Fl_Counter*, void*);
  static void cb_mCounter(Fl_Counter*, void*);
public:
  Fl_Smart_Tile *mSmartTile;
  short h();
  short w();
  void show();
  void redraw();
  void add( Fl_Widget* widget );
  void add( Fl_Widget& widget );
  void remove( Fl_Widget* widget );
  SigSlot::Signalv0 mNewPosition;
};
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Menu_Button.H>

class UserInterface {
public:
  public: CLAMGUI::SMSTools* mSMS;
  UserInterface();
  Fl_Window *mWindow;
private:
  inline void cb_Open_i(Fl_Button*, void*);
  static void cb_Open(Fl_Button*, void*);
  inline void cb_Edit_i(Fl_Button*, void*);
  static void cb_Edit(Fl_Button*, void*);
  inline void cb_Save_i(Fl_Button*, void*);
  static void cb_Save(Fl_Button*, void*);
public:
  Fl_SMS_Arrow *mAnalysisDataFromProcess;
  Fl_SMS_Arrow *mAnalysisDataFromFile;
  Fl_Menu_Button *mSegmentButton;
  static Fl_Menu_Item menu_mSegmentButton[];
private:
  inline void cb_Show_i(Fl_Menu_*, void*);
  static void cb_Show(Fl_Menu_*, void*);
  inline void cb_Show1_i(Fl_Menu_*, void*);
  static void cb_Show1(Fl_Menu_*, void*);
  inline void cb_Show2_i(Fl_Menu_*, void*);
  static void cb_Show2(Fl_Menu_*, void*);
  Fl_File_Button *mFirstSegmentButton;
  inline void cb_mFirstSegmentButton_i(Fl_File_Button*, void*);
  static void cb_mFirstSegmentButton(Fl_File_Button*, void*);
  Fl_Box *mSecondSegmentButton;
  Fl_File_Button *mStoreSMSSynthSound;
  inline void cb_mStoreSMSSynthSound_i(Fl_File_Button*, void*);
  static void cb_mStoreSMSSynthSound(Fl_File_Button*, void*);
  Fl_File_Button *mStoreSMSSynthSinusoidal;
  inline void cb_mStoreSMSSynthSinusoidal_i(Fl_File_Button*, void*);
  static void cb_mStoreSMSSynthSinusoidal(Fl_File_Button*, void*);
  Fl_File_Button *mStoreSMSSynthResidual;
  inline void cb_mStoreSMSSynthResidual_i(Fl_File_Button*, void*);
  static void cb_mStoreSMSSynthResidual(Fl_File_Button*, void*);
  Fl_Button *mSMSTransformationButton;
  inline void cb_mSMSTransformationButton_i(Fl_Button*, void*);
  static void cb_mSMSTransformationButton(Fl_Button*, void*);
public:
  Fl_Button *mStoreAnalysis;
private:
  inline void cb_mStoreAnalysis_i(Fl_Button*, void*);
  static void cb_mStoreAnalysis(Fl_Button*, void*);
  Fl_Button *mSMSSynthesisButton;
  inline void cb_mSMSSynthesisButton_i(Fl_Button*, void*);
  static void cb_mSMSSynthesisButton(Fl_Button*, void*);
public:
  Fl_Button *mStoreTransformation;
private:
  inline void cb_mStoreTransformation_i(Fl_Button*, void*);
  static void cb_mStoreTransformation(Fl_Button*, void*);
  Fl_Button *mSMSAnalysisButton;
  inline void cb_mSMSAnalysisButton_i(Fl_Button*, void*);
  static void cb_mSMSAnalysisButton(Fl_Button*, void*);
  inline void cb_Open1_i(Fl_Button*, void*);
  static void cb_Open1(Fl_Button*, void*);
  Fl_Display_Button *mAudioInButton;
  inline void cb_mAudioInButton_i(Fl_Display_Button*, void*);
  static void cb_mAudioInButton(Fl_Display_Button*, void*);
  Fl_Display_Button *mShowSynthesizedAudio;
  inline void cb_mShowSynthesizedAudio_i(Fl_Display_Button*, void*);
  static void cb_mShowSynthesizedAudio(Fl_Display_Button*, void*);
  Fl_Display_Button *mShowSynthesizedSinusoidal;
  inline void cb_mShowSynthesizedSinusoidal_i(Fl_Display_Button*, void*);
  static void cb_mShowSynthesizedSinusoidal(Fl_Display_Button*, void*);
  Fl_Display_Button *mShowSynthesizedResidual;
  inline void cb_mShowSynthesizedResidual_i(Fl_Display_Button*, void*);
  static void cb_mShowSynthesizedResidual(Fl_Display_Button*, void*);
  Fl_Button *mExtractMelody;
  inline void cb_mExtractMelody_i(Fl_Button*, void*);
  static void cb_mExtractMelody(Fl_Button*, void*);
  Fl_File_Button *mStoreMelodyButton;
  inline void cb_mStoreMelodyButton_i(Fl_File_Button*, void*);
  static void cb_mStoreMelodyButton(Fl_File_Button*, void*);
  inline void cb__i(Fl_File_Button*, void*);
  static void cb_(Fl_File_Button*, void*);
  Fl_Button *mSMSTransformationLoad;
  inline void cb_mSMSTransformationLoad_i(Fl_Button*, void*);
  static void cb_mSMSTransformationLoad(Fl_Button*, void*);
  Fl_Button *mSMSTransformationUndo;
  inline void cb_mSMSTransformationUndo_i(Fl_Button*, void*);
  static void cb_mSMSTransformationUndo(Fl_Button*, void*);
  Fl_Smart_Tile *mSmartTile;
public:
  Fl_Counter *mCounter;
private:
  inline void cb_mCounter1_i(Fl_Counter*, void*);
  static void cb_mCounter1(Fl_Counter*, void*);
public:
  void Init(void);
private:
  void LoadConfiguration(void);
  void EditConfiguration(void);
  void StoreConfiguration(void);
  void Analyze(void);
  void LoadAnalysisData(void);
  void StoreAnalysisData(void);
  void StoreTransformationData(void);
  void Synthesize(void);
  void AnalyzeMelody(void);
  void StoreMelody(void);
  void StoreOutputSound(void);
  void StoreOutputSoundResidual(void);
  void StoreOutputSoundSinusoidal(void);
  void LoadTransformation(void);
  void Transform(void);
  void Exit(void);
  bool LoadSound();
public:
  bool LoadSelectedSound();
private:
  void ChangeFrame();
  void ChangeTimeTag(double tag);
  void DisplayInputSound();
  void Update();
  void DisplaySinusoidalTracks();
  void DisplaySpectrumAndPeaks();
  void DisplaySinusoidalSpectrum();
  void DisplayResidualSpectrum();
  void DisplaySynthesizedAudio();
  void DisplaySynthesizedSinusoidal();
  void DisplaySynthesizedResidual();
  void ApplyInitialState();
  void ApplyReadyToAnalyzeState();
  void ApplyAnalysisAvailableState();
  void ApplyMelodyAvailableState();
  void ApplyTransformationReadyState();
  void ApplySynthesisAvailableState();
  void ApplyTransformationPerformedState();
  void DeactivateFrameDataMenuItems();
  bool mFrameDataAvailable;
public:
  bool FrameDataAvailable();
private:
  void UndoTransform();
};
#endif
