// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef UserInterface_hxx
#define UserInterface_hxx
#include <FL/Fl.H>
#include <FL/Fl_Tile.H>
#include "Fl_Smart_Tile.hxx"
class Fl_Smart_Tile;
#include "ForwardDeclarations.hxx"
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Box.H>

class UserInterface {
public:
  public: CLAMGUI::AnalysisSynthesisExampleGUI* mAnalysisSynthesisExample;
  UserInterface();
  Fl_Window *mWindow;
private:
  Fl_Menu_Bar *mMenuBar;
  static Fl_Menu_Item menu_mMenuBar[];
  inline void cb_Load_i(Fl_Menu_*, void*);
  static void cb_Load(Fl_Menu_*, void*);
  inline void cb_Edit_i(Fl_Menu_*, void*);
  static void cb_Edit(Fl_Menu_*, void*);
  inline void cb_Store_i(Fl_Menu_*, void*);
  static void cb_Store(Fl_Menu_*, void*);
  inline void cb_Exit_i(Fl_Menu_*, void*);
  static void cb_Exit(Fl_Menu_*, void*);
  static Fl_Menu_Item *mAnalyze;
  inline void cb_mAnalyze_i(Fl_Menu_*, void*);
  static void cb_mAnalyze(Fl_Menu_*, void*);
  inline void cb_Load1_i(Fl_Menu_*, void*);
  static void cb_Load1(Fl_Menu_*, void*);
  static Fl_Menu_Item *mStoreAnalysisData;
  inline void cb_mStoreAnalysisData_i(Fl_Menu_*, void*);
  static void cb_mStoreAnalysisData(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMelodySM;
  static Fl_Menu_Item *mMelodyAnalyze;
  inline void cb_mMelodyAnalyze_i(Fl_Menu_*, void*);
  static void cb_mMelodyAnalyze(Fl_Menu_*, void*);
  static Fl_Menu_Item *mMelodyStore;
  inline void cb_mMelodyStore_i(Fl_Menu_*, void*);
  static void cb_mMelodyStore(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSinTracksDisplay;
  inline void cb_mSinTracksDisplay_i(Fl_Menu_*, void*);
  static void cb_mSinTracksDisplay(Fl_Menu_*, void*);
  inline void cb_Load2_i(Fl_Menu_*, void*);
  static void cb_Load2(Fl_Menu_*, void*);
  static Fl_Menu_Item *mDoTransformation;
  inline void cb_mDoTransformation_i(Fl_Menu_*, void*);
  static void cb_mDoTransformation(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSynthesize;
  inline void cb_Synthesize_i(Fl_Menu_*, void*);
  static void cb_Synthesize(Fl_Menu_*, void*);
  static Fl_Menu_Item *mStoreOutputs;
  inline void cb_Sound_i(Fl_Menu_*, void*);
  static void cb_Sound(Fl_Menu_*, void*);
  inline void cb_Sinusoidal_i(Fl_Menu_*, void*);
  static void cb_Sinusoidal(Fl_Menu_*, void*);
  inline void cb_Residual_i(Fl_Menu_*, void*);
  static void cb_Residual(Fl_Menu_*, void*);
  static Fl_Menu_Item *mViewMenuItem;
  static Fl_Menu_Item *mShowOriginalAudioItem;
  inline void cb_mShowOriginalAudioItem_i(Fl_Menu_*, void*);
  static void cb_mShowOriginalAudioItem(Fl_Menu_*, void*);
  static Fl_Menu_Item *mShowSinTracksItem;
  inline void cb_mShowSinTracksItem_i(Fl_Menu_*, void*);
  static void cb_mShowSinTracksItem(Fl_Menu_*, void*);
  static Fl_Menu_Item *mShowSpectrumAndPeaksItem;
  inline void cb_mShowSpectrumAndPeaksItem_i(Fl_Menu_*, void*);
  static void cb_mShowSpectrumAndPeaksItem(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *mShowSinusoidalSpectrumItem;
private:
  inline void cb_mShowSinusoidalSpectrumItem_i(Fl_Menu_*, void*);
  static void cb_mShowSinusoidalSpectrumItem(Fl_Menu_*, void*);
  static Fl_Menu_Item *mShowResidualSpectrumItem;
  inline void cb_mShowResidualSpectrumItem_i(Fl_Menu_*, void*);
  static void cb_mShowResidualSpectrumItem(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSynthesizedAudioItem;
  inline void cb_mSynthesizedAudioItem_i(Fl_Menu_*, void*);
  static void cb_mSynthesizedAudioItem(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSynthesizedSinusoidalItem;
  inline void cb_mSynthesizedSinusoidalItem_i(Fl_Menu_*, void*);
  static void cb_mSynthesizedSinusoidalItem(Fl_Menu_*, void*);
  static Fl_Menu_Item *mSynthesizedResidualItem;
  inline void cb_mSynthesizedResidualItem_i(Fl_Menu_*, void*);
  static void cb_mSynthesizedResidualItem(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *mHelpItem;
private:
  inline void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
public:
  Fl_Counter *mCounter;
private:
  inline void cb_mCounter_i(Fl_Counter*, void*);
  static void cb_mCounter(Fl_Counter*, void*);
  Fl_Smart_Tile *mSmartTile;
  void AboutWindow();
  Fl_Window *mWindow2;
  inline void cb_mWindow2_i(Fl_Window*, void*);
  static void cb_mWindow2(Fl_Window*, void*);
public:
  void Init(void);
private:
  void LoadConfiguration(void);
  void EditConfiguration(void);
  void StoreConfiguration(void);
  void Analyze(void);
  void LoadAnalysisData(void);
  void StoreAnalysisData(void);
  void Synthesize(void);
  void AnalyzeMelody(void);
  void StoreMelody(void);
  void StoreOutputSound(void);
  void StoreOutputSoundResidual(void);
  void StoreOutputSoundSinusoidal(void);
  void LoadTransformation(void);
  void Transform(void);
  void Exit(void);
  void LoadSound();
  void ChangeFrame();
  void ChangeTimeTag(double tag);
  void DisplayInputSound();
  void Update();
  void DisplaySinusoidalTracks();
  void DisplaySpectrumAndPeaks();
  void DisplaySinusoidalSpectrum();
  void DisplayResidualSpectrum();
  void DisplaySynthesizedAudio();
  void DisplaySynthesizedSinusoidal();
  void DisplaySynthesizedResidual();
};
#endif
