// generated by Fast Light User Interface Designer (fluid) version 1.0011

#include "UserInterface.hxx"
#include "SMSAnalysisSynthesisConfig.hxx"

inline void Configuration::cb_mWindow_i(Fl_Window*, void*) {
  delete mWindow;
}
void Configuration::cb_mWindow(Fl_Window* o, void* v) {
  ((Configuration*)(o->user_data()))->cb_mWindow_i(o,v);
}

inline void Configuration::cb_Hop_i(Fl_Value_Input* o, void*) {
  mConfig->SetAnalysisHopSize(o->value());
}
void Configuration::cb_Hop(Fl_Value_Input* o, void* v) {
  ((Configuration*)(o->parent()->user_data()))->cb_Hop_i(o,v);
}

inline void Configuration::cb_Analysis_i(Fl_Choice* o, void*) {
  printf("Value= %d\n",atoi(o->text()));
mConfig->SetAnalysisWindowSize(o->value()*512);
}
void Configuration::cb_Analysis(Fl_Choice* o, void* v) {
  ((Configuration*)(o->parent()->user_data()))->cb_Analysis_i(o,v);
}

Fl_Menu_Item Configuration::menu_Analysis[] = {
 {"512", 0,  0, 0, 0, 0, 0, 12, 0},
 {"1024", 0,  0, 0, 0, 0, 0, 12, 0},
 {"2048", 0,  0, 0, 0, 0, 0, 12, 0},
 {"4096", 0,  0, 0, 0, 0, 0, 12, 0},
 {"8192", 0,  0, 0, 0, 0, 0, 12, 0},
 {0}
};

Fl_Menu_Item Configuration::menu_Analysis1[] = {
 {"Kaiser-Bessel 17", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 18", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 19", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 20", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 25", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 30", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 35", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 74", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 62", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 70", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 92", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Hamming", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Triangular", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 92 Trans Main Lobe", 0,  0, 0, 0, 0, 0, 12, 0},
 {0}
};

inline void Configuration::cb_Residual_i(Fl_Choice* o, void*) {
  printf("Value= %d\n",atoi(o->text()));
mConfig->SetAnalysisWindowSize(o->value()*512);
}
void Configuration::cb_Residual(Fl_Choice* o, void* v) {
  ((Configuration*)(o->parent()->user_data()))->cb_Residual_i(o,v);
}

Fl_Menu_Item Configuration::menu_Residual[] = {
 {"512", 0,  0, 0, 0, 0, 0, 12, 0},
 {"1024", 0,  0, 0, 0, 0, 0, 12, 0},
 {"2048", 0,  0, 0, 0, 0, 0, 12, 0},
 {"4096", 0,  0, 0, 0, 0, 0, 12, 0},
 {"8192", 0,  0, 0, 0, 0, 0, 12, 0},
 {0}
};

Fl_Menu_Item Configuration::menu_Residual1[] = {
 {"Kaiser-Bessel 17", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 18", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 19", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 20", 0,  0, 0, 0, 0, 0, 13, 0},
 {"Kaiser-Bessel 25", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 30", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 35", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 74", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 62", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 70", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 92", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Hamming", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Triangular", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 92 Trans Main Lobe", 0,  0, 0, 0, 0, 0, 12, 0},
 {0}
};

inline void Configuration::cb_Window_i(Fl_Choice* o, void*) {
  printf("Value= %d\n",atoi(o->text()));
mConfig->SetAnalysisWindowSize(o->value()*512);
}
void Configuration::cb_Window(Fl_Choice* o, void* v) {
  ((Configuration*)(o->parent()->user_data()))->cb_Window_i(o,v);
}

Fl_Menu_Item Configuration::menu_Window[] = {
 {"512", 0,  0, 0, 0, 0, 0, 12, 0},
 {"1024", 0,  0, 0, 0, 0, 0, 12, 0},
 {"2048", 0,  0, 0, 0, 0, 0, 12, 0},
 {"4096", 0,  0, 0, 0, 0, 0, 12, 0},
 {"8192", 0,  0, 0, 0, 0, 0, 12, 0},
 {0}
};

Fl_Menu_Item Configuration::menu_Window1[] = {
 {"Kaiser-Bessel 17", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 18", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 19", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 20", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 25", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 30", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Kaiser-Bessel 35", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 74", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 62", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 70", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 92", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Hamming", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Triangular", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Blackman-Harris 92 Trans Main Lobe", 0,  0, 0, 0, 0, 0, 12, 0},
 {0}
};

inline void Configuration::cb_Hop1_i(Fl_Value_Input* o, void*) {
  mConfig->SetAnalysisHopSize(o->value());
}
void Configuration::cb_Hop1(Fl_Value_Input* o, void* v) {
  ((Configuration*)(o->parent()->user_data()))->cb_Hop1_i(o,v);
}

inline void Configuration::cb_Zero_i(Fl_Value_Input* o, void*) {
  mConfig->SetAnalysisHopSize(o->value());
}
void Configuration::cb_Zero(Fl_Value_Input* o, void* v) {
  ((Configuration*)(o->parent()->user_data()))->cb_Zero_i(o,v);
}

Fl_Menu_Item Configuration::menu_Phase[] = {
 {"Align", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Random", 0,  0, 0, 0, 0, 0, 12, 0},
 {"Continuation", 0,  0, 0, 0, 0, 0, 12, 0},
 {0}
};

Configuration::Configuration(CLAM::SMSAnalysisSynthesisConfig* config) {
  Fl_Window* w;
  mConfig = config;
  { Fl_Window* o = mWindow = new Fl_Window(536, 740, "Configure the Analysis/Synthesis parameters");
    w = o;
    o->color(16);
    o->callback((Fl_Callback*)cb_mWindow, (void*)(this));
    { Fl_Box* o = new Fl_Box(10, 15, 515, 115);
      o->box(FL_SHADOW_BOX);
      o->color(16);
      o->labeltype(FL_NO_LABEL);
    }
    { Fl_Box* o = new Fl_Box(15, 5, 120, 20, "Input & Output Files");
      o->box(FL_FLAT_BOX);
      o->color(16);
      o->labelsize(12);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { Fl_Input* o = mFileInName = new Fl_Input(115, 25, 355, 20, "Input Sound File:");
      o->labelsize(12);
      o->textsize(12);
    }
    { Fl_Input* o = mFileOutName = new Fl_Input(125, 50, 345, 20, "Output Sound File:");
      o->labelsize(12);
      o->textsize(12);
    }
    { Fl_Input* o = mXMLInName = new Fl_Input(105, 75, 365, 20, "Input XML File:");
      o->labelsize(12);
      o->textsize(12);
    }
    { Fl_Input* o = mXMLOutName = new Fl_Input(115, 100, 355, 20, "Output XML File:");
      o->labelsize(12);
      o->textsize(12);
    }
    { Fl_Box* o = new Fl_Box(10, 145, 515, 325);
      o->box(FL_SHADOW_BOX);
      o->color(16);
      o->labeltype(FL_NO_LABEL);
    }
    { Fl_Box* o = new Fl_Box(15, 135, 120, 20, "Analysis Parameters");
      o->box(FL_FLAT_BOX);
      o->color(16);
      o->labelsize(12);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { Fl_Value_Input* o = new Fl_Value_Input(75, 240, 80, 20, "Hop size:");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_Hop);
    }
    { Fl_Choice* o = new Fl_Choice(20, 170, 235, 20, "Analysis Window Size:");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_Analysis);
      o->align(FL_ALIGN_TOP_LEFT);
      o->menu(menu_Analysis);
    }
    { Fl_Choice* o = new Fl_Choice(20, 210, 235, 20, "Analysis Window Type:");
      o->labelsize(12);
      o->textsize(12);
      o->align(FL_ALIGN_TOP_LEFT);
      o->menu(menu_Analysis1);
    }
    { Fl_Choice* o = new Fl_Choice(280, 170, 235, 20, "Residual Window Size:");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_Residual);
      o->align(FL_ALIGN_TOP_LEFT);
      o->menu(menu_Residual);
    }
    { Fl_Choice* o = new Fl_Choice(280, 210, 235, 20, "Residual Window Type:");
      o->labelsize(12);
      o->textsize(12);
      o->align(FL_ALIGN_TOP_LEFT);
      o->menu(menu_Residual1);
    }
    { Fl_Value_Slider* o = new Fl_Value_Slider(140, 270, 375, 20, "Zero Padding Factor:");
      o->type(3);
      o->color(16);
      o->selection_color(24);
      o->labelsize(12);
      o->maximum(10000);
      o->step(10);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Light_Button* o = new Fl_Light_Button(20, 440, 130, 20, "Analysis Harmonic");
      o->labelsize(12);
    }
    { Fl_Light_Button* o = new Fl_Light_Button(395, 440, 120, 20, "Do Clean Tracks");
      o->labelsize(12);
    }
    { Fl_Box* o = new Fl_Box(10, 485, 515, 140);
      o->box(FL_SHADOW_BOX);
      o->color(16);
      o->labeltype(FL_NO_LABEL);
    }
    { Fl_Box* o = new Fl_Box(20, 475, 125, 20, "Synthesis Parameters");
      o->box(FL_FLAT_BOX);
      o->color(16);
      o->labelsize(12);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { Fl_Choice* o = new Fl_Choice(95, 495, 235, 20, "Window Size:");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_Window);
      o->menu(menu_Window);
    }
    { Fl_Choice* o = new Fl_Choice(100, 520, 235, 20, "Window Type:");
      o->labelsize(12);
      o->textsize(12);
      o->menu(menu_Window1);
    }
    { Fl_Value_Input* o = new Fl_Value_Input(75, 545, 80, 20, "Hop size: ");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_Hop1);
    }
    { Fl_Value_Input* o = new Fl_Value_Input(140, 570, 80, 20, "Zero Padding Factor:");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_Zero);
    }
    { Fl_Choice* o = new Fl_Choice(165, 595, 235, 20, "Phase Management Type:");
      o->labelsize(12);
      o->textsize(12);
      o->menu(menu_Phase);
    }
    { Fl_Button* o = new Fl_Button(215, 705, 155, 25, "Dump on an XML File...");
      o->labelsize(12);
    }
    { Fl_Button* o = new Fl_Button(390, 705, 135, 25, "Set Configuration");
      o->labelsize(12);
    }
    { Fl_Button* o = new Fl_Button(35, 705, 155, 25, "Load from an XML File...");
      o->labelsize(12);
    }
    mWindow->show();
    o->end();
  }
}

inline void UserInterface::cb_Configure_i(Fl_Menu_*, void*) {
  LoadConfiguration();
//EditConfiguration();
}
void UserInterface::cb_Configure(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Configure_i(o,v);
}

inline void UserInterface::cb_Edit_i(Fl_Menu_*, void*) {
  EditConfiguration();
}
void UserInterface::cb_Edit(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Edit_i(o,v);
}

inline void UserInterface::cb_Load_i(Fl_Menu_*, void*) {
  LoadAnalysisData();
}
void UserInterface::cb_Load(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

inline void UserInterface::cb_mStoreAnalysisData_i(Fl_Menu_*, void*) {
  StoreAnalysisData();
}
void UserInterface::cb_mStoreAnalysisData(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mStoreAnalysisData_i(o,v);
}

inline void UserInterface::cb_Load1_i(Fl_Menu_*, void*) {
  LoadTransformation();
}
void UserInterface::cb_Load1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Load1_i(o,v);
}

inline void UserInterface::cb_mDoTransformation_i(Fl_Menu_*, void*) {
  Transform();
}
void UserInterface::cb_mDoTransformation(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mDoTransformation_i(o,v);
}

inline void UserInterface::cb_mMelodyAnalyze_i(Fl_Menu_*, void*) {
  AnalyzeMelody();
}
void UserInterface::cb_mMelodyAnalyze(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mMelodyAnalyze_i(o,v);
}

inline void UserInterface::cb_mMelodyStore_i(Fl_Menu_*, void*) {
  StoreMelody();
}
void UserInterface::cb_mMelodyStore(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mMelodyStore_i(o,v);
}

inline void UserInterface::cb_mDisplayInSound_i(Fl_Menu_*, void*) {
  DisplayInputSound();
}
void UserInterface::cb_mDisplayInSound(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mDisplayInSound_i(o,v);
}

inline void UserInterface::cb_mDisplayInSpec_i(Fl_Menu_*, void*) {
  DisplayInputSpectrum();
}
void UserInterface::cb_mDisplayInSpec(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mDisplayInSpec_i(o,v);
}

inline void UserInterface::cb_mPlayInputSound_i(Fl_Menu_*, void*) {
  PlayInputSound();
}
void UserInterface::cb_mPlayInputSound(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mPlayInputSound_i(o,v);
}

inline void UserInterface::cb_mAnalyze_i(Fl_Menu_*, void*) {
  Analyze();
}
void UserInterface::cb_mAnalyze(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mAnalyze_i(o,v);
}

inline void UserInterface::cb_mSynthesize_i(Fl_Menu_*, void*) {
  Synthesize();
}
void UserInterface::cb_mSynthesize(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mSynthesize_i(o,v);
}

inline void UserInterface::cb_Sound_i(Fl_Menu_*, void*) {
  StoreOutputSound();
}
void UserInterface::cb_Sound(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Sound_i(o,v);
}

inline void UserInterface::cb_Sinusoidal_i(Fl_Menu_*, void*) {
  StoreOutputSoundSinusoidal();
}
void UserInterface::cb_Sinusoidal(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Sinusoidal_i(o,v);
}

inline void UserInterface::cb_Residual1_i(Fl_Menu_*, void*) {
  StoreOutputSoundResidual();
}
void UserInterface::cb_Residual1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Residual1_i(o,v);
}

inline void UserInterface::cb_Sound1_i(Fl_Menu_*, void*) {
  DisplayOutputSound();
}
void UserInterface::cb_Sound1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Sound1_i(o,v);
}

inline void UserInterface::cb_Sinusoidal1_i(Fl_Menu_*, void*) {
  DisplayOutputSoundSinusoidal();
}
void UserInterface::cb_Sinusoidal1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Sinusoidal1_i(o,v);
}

inline void UserInterface::cb_Residual2_i(Fl_Menu_*, void*) {
  DisplayOutputSoundResidual();
}
void UserInterface::cb_Residual2(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Residual2_i(o,v);
}

inline void UserInterface::cb_Sound2_i(Fl_Menu_*, void*) {
  PlayOutputSound();
}
void UserInterface::cb_Sound2(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Sound2_i(o,v);
}

inline void UserInterface::cb_Sinusoidal2_i(Fl_Menu_*, void*) {
  PlaySinusoidal();
}
void UserInterface::cb_Sinusoidal2(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Sinusoidal2_i(o,v);
}

inline void UserInterface::cb_Residual3_i(Fl_Menu_*, void*) {
  PlayResidual();
}
void UserInterface::cb_Residual3(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Residual3_i(o,v);
}

inline void UserInterface::cb_Exit_i(Fl_Menu_*, void*) {
  if(mWindow2!=NULL) delete mWindow2;
Exit();
}
void UserInterface::cb_Exit(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Exit_i(o,v);
}

inline void UserInterface::cb_About_i(Fl_Menu_*, void*) {
  AboutWindow();
}
void UserInterface::cb_About(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_About_i(o,v);
}

Fl_Menu_Item UserInterface::menu_mMenuBar[] = {
 {"Input", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Configure...", 0,  (Fl_Callback*)UserInterface::cb_Configure, 0, 0, 0, 0, 12, 0},
 {"Edit Configure...", 0,  (Fl_Callback*)UserInterface::cb_Edit, 0, 0, 0, 0, 12, 0},
 {"Analysis Data", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Load...", 0,  (Fl_Callback*)UserInterface::cb_Load, 0, 0, 0, 0, 12, 0},
 {"Store...", 0,  (Fl_Callback*)UserInterface::cb_mStoreAnalysisData, 0, 1, 0, 0, 12, 0},
 {0},
 {"Transformation", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Load...", 0,  (Fl_Callback*)UserInterface::cb_Load1, 0, 0, 0, 0, 12, 0},
 {"Do", 0,  (Fl_Callback*)UserInterface::cb_mDoTransformation, 0, 1, 0, 0, 12, 0},
 {0},
 {"Melody", 0,  0, 0, 65, 0, 0, 12, 0},
 {"Analyze", 0,  (Fl_Callback*)UserInterface::cb_mMelodyAnalyze, 0, 0, 0, 0, 12, 0},
 {"Store", 0,  (Fl_Callback*)UserInterface::cb_mMelodyStore, 0, 1, 0, 0, 12, 0},
 {0},
 {"Display", 0,  0, 0, 65, 0, 0, 12, 0},
 {"Sound", 0,  (Fl_Callback*)UserInterface::cb_mDisplayInSound, 0, 1, 0, 0, 12, 0},
 {"Spectrum", 0,  (Fl_Callback*)UserInterface::cb_mDisplayInSpec, 0, 1, 0, 0, 12, 0},
 {0},
 {"Play", 0,  (Fl_Callback*)UserInterface::cb_mPlayInputSound, 0, 1, 0, 0, 12, 0},
 {0},
 {"Analyze", 0x40061,  (Fl_Callback*)UserInterface::cb_mAnalyze, 0, 1, 0, 0, 12, 0},
 {"Synthesize", 0x40073,  (Fl_Callback*)UserInterface::cb_mSynthesize, 0, 1, 0, 0, 12, 0},
 {"Output", 0,  0, 0, 65, 0, 0, 12, 0},
 {"Store", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Sound", 0,  (Fl_Callback*)UserInterface::cb_Sound, 0, 0, 0, 0, 12, 0},
 {"Sinusoidal", 0,  (Fl_Callback*)UserInterface::cb_Sinusoidal, 0, 0, 0, 0, 12, 0},
 {"Residual", 0,  (Fl_Callback*)UserInterface::cb_Residual1, 0, 0, 0, 0, 12, 0},
 {0},
 {"Display", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Sound", 0,  (Fl_Callback*)UserInterface::cb_Sound1, 0, 0, 0, 0, 12, 0},
 {"Sinusoidal", 0,  (Fl_Callback*)UserInterface::cb_Sinusoidal1, 0, 0, 0, 0, 12, 0},
 {"Residual", 0,  (Fl_Callback*)UserInterface::cb_Residual2, 0, 0, 0, 0, 12, 0},
 {0},
 {"Play", 0,  0, 0, 65, 0, 0, 12, 0},
 {"Sound", 0,  (Fl_Callback*)UserInterface::cb_Sound2, 0, 0, 0, 0, 12, 0},
 {"Sinusoidal", 0,  (Fl_Callback*)UserInterface::cb_Sinusoidal2, 0, 0, 0, 0, 12, 0},
 {"Residual", 0,  (Fl_Callback*)UserInterface::cb_Residual3, 0, 0, 0, 0, 12, 0},
 {0},
 {0},
 {"Exit", 0x40071,  (Fl_Callback*)UserInterface::cb_Exit, 0, 0, 0, 0, 12, 0},
 {"About", 0,  (Fl_Callback*)UserInterface::cb_About, 0, 0, 0, 13, 12, 0},
 {0}
};
Fl_Menu_Item* UserInterface::mStoreAnalysisData = UserInterface::menu_mMenuBar + 5;
Fl_Menu_Item* UserInterface::mDoTransformation = UserInterface::menu_mMenuBar + 9;
Fl_Menu_Item* UserInterface::mMelodySM = UserInterface::menu_mMenuBar + 11;
Fl_Menu_Item* UserInterface::mMelodyAnalyze = UserInterface::menu_mMenuBar + 12;
Fl_Menu_Item* UserInterface::mMelodyStore = UserInterface::menu_mMenuBar + 13;
Fl_Menu_Item* UserInterface::mDisplayInSM = UserInterface::menu_mMenuBar + 15;
Fl_Menu_Item* UserInterface::mDisplayInSound = UserInterface::menu_mMenuBar + 16;
Fl_Menu_Item* UserInterface::mDisplayInSpec = UserInterface::menu_mMenuBar + 17;
Fl_Menu_Item* UserInterface::mPlayInputSound = UserInterface::menu_mMenuBar + 19;
Fl_Menu_Item* UserInterface::mAnalyze = UserInterface::menu_mMenuBar + 21;
Fl_Menu_Item* UserInterface::mSynthesize = UserInterface::menu_mMenuBar + 22;
Fl_Menu_Item* UserInterface::mOutputSM = UserInterface::menu_mMenuBar + 23;
Fl_Menu_Item* UserInterface::mStoreOutputs = UserInterface::menu_mMenuBar + 24;
Fl_Menu_Item* UserInterface::mVisualizeOutputs = UserInterface::menu_mMenuBar + 29;
Fl_Menu_Item* UserInterface::mPlayOutputs = UserInterface::menu_mMenuBar + 34;

inline void UserInterface::cb_mWindow2_i(Fl_Window*, void*) {
  delete mWindow2;
mWindow2=NULL;
}
void UserInterface::cb_mWindow2(Fl_Window* o, void* v) {
  ((UserInterface*)(o->user_data()))->cb_mWindow2_i(o,v);
}

UserInterface::UserInterface() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = mWindow = new Fl_Double_Window(1114, 796, "SMS Analysis/Synthesis Application | MTG-UPF (Barcelona)");
    w = o;
    o->color(23);
    o->user_data((void*)(this));
    { Fl_Input* o = mConfigurationText = new Fl_Input(105, 25, 985, 20, "Configuration File");
      o->box(FL_THIN_DOWN_BOX);
      o->labelsize(12);
      o->textsize(12);
      o->align(132);
    }
    { Fl_Menu_Bar* o = mMenuBar = new Fl_Menu_Bar(0, 0, 1110, 20);
      o->box(FL_THIN_UP_BOX);
      o->labelsize(13);
      o->textsize(12);
      o->menu(menu_mMenuBar);
    }
    { Fl_Smart_Tile* o = mSmartTile = new Fl_Smart_Tile(5, 50, 1095, 725);
      o->color(23);
      Fl_Group::current()->resizable(o);
    }
    mWindow2=NULL;
    o->end();
  }
}

void UserInterface::AboutWindow() {
  Fl_Window* w;
  { Fl_Window* o = mWindow2 = new Fl_Window(417, 100, "About this program...");
    w = o;
    o->box(FL_ENGRAVED_BOX);
    o->color(17);
    o->labeltype(FL_NORMAL_LABEL);
    o->labelsize(10);
    o->callback((Fl_Callback*)cb_mWindow2, (void*)(this));
    { Fl_Box* o = new Fl_Box(85, 15, 265, 20, "SMS Analysis/Synthesis Application");
      o->labelfont(3);
      o->labelsize(12);
    }
    { Fl_Box* o = new Fl_Box(85, 40, 265, 20, "by MTG - IUA - UPF (Barcelona, Spain)");
      o->labelfont(2);
      o->labelsize(12);
    }
    new Fl_Box(360, 15, 50, 60, "logos/iua.xpm");
    { Fl_Box* o = new Fl_Box(90, 65, 260, 20, "please visit us at http://www.iua.upf.es/mtg for more info");
      o->labelfont(2);
      o->labelsize(11);
    }
    new Fl_Box(10, 20, 75, 55, "logos/mtg.xpm");
    mWindow2->show();
    o->clear_border();
    o->end();
  }
}
