// generated by Fast Light User Interface Designer (fluid) version 1.0011

#include "UserInterface.hxx"
#include "SMSAnalysisSynthesisConfig.hxx"

inline void UserInterface::cb_Load_i(Fl_Menu_*, void*) {
  LoadConfiguration();
}
void UserInterface::cb_Load(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

inline void UserInterface::cb_Edit_i(Fl_Menu_*, void*) {
  EditConfiguration();
}
void UserInterface::cb_Edit(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Edit_i(o,v);
}

inline void UserInterface::cb_Store_i(Fl_Menu_*, void*) {
  StoreConfiguration();
}
void UserInterface::cb_Store(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Store_i(o,v);
}

inline void UserInterface::cb_Exit_i(Fl_Menu_*, void*) {
  if(mWindow2!=NULL) delete mWindow2;
Exit();
}
void UserInterface::cb_Exit(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Exit_i(o,v);
}

inline void UserInterface::cb_mAnalyze_i(Fl_Menu_*, void*) {
  Analyze();
}
void UserInterface::cb_mAnalyze(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mAnalyze_i(o,v);
}

inline void UserInterface::cb_Load1_i(Fl_Menu_*, void*) {
  LoadAnalysisData();
}
void UserInterface::cb_Load1(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Load1_i(o,v);
}

inline void UserInterface::cb_mStoreAnalysisData_i(Fl_Menu_*, void*) {
  StoreAnalysisData();
}
void UserInterface::cb_mStoreAnalysisData(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mStoreAnalysisData_i(o,v);
}

inline void UserInterface::cb_mMelodyAnalyze_i(Fl_Menu_*, void*) {
  AnalyzeMelody();
}
void UserInterface::cb_mMelodyAnalyze(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mMelodyAnalyze_i(o,v);
}

inline void UserInterface::cb_mMelodyStore_i(Fl_Menu_*, void*) {
  StoreMelody();
}
void UserInterface::cb_mMelodyStore(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mMelodyStore_i(o,v);
}

inline void UserInterface::cb_mSinTracksDisplay_i(Fl_Menu_*, void*) {
  DisplaySinusoidalTracks();
}
void UserInterface::cb_mSinTracksDisplay(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mSinTracksDisplay_i(o,v);
}

inline void UserInterface::cb_Load2_i(Fl_Menu_*, void*) {
  LoadTransformation();
}
void UserInterface::cb_Load2(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Load2_i(o,v);
}

inline void UserInterface::cb_mDoTransformation_i(Fl_Menu_*, void*) {
  Transform();
}
void UserInterface::cb_mDoTransformation(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mDoTransformation_i(o,v);
}

inline void UserInterface::cb_Synthesize_i(Fl_Menu_*, void*) {
  Synthesize();
}
void UserInterface::cb_Synthesize(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Synthesize_i(o,v);
}

inline void UserInterface::cb_Sound_i(Fl_Menu_*, void*) {
  StoreOutputSound();
}
void UserInterface::cb_Sound(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Sound_i(o,v);
}

inline void UserInterface::cb_Sinusoidal_i(Fl_Menu_*, void*) {
  StoreOutputSoundSinusoidal();
}
void UserInterface::cb_Sinusoidal(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Sinusoidal_i(o,v);
}

inline void UserInterface::cb_Residual_i(Fl_Menu_*, void*) {
  StoreOutputSoundResidual();
}
void UserInterface::cb_Residual(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Residual_i(o,v);
}

inline void UserInterface::cb_mShowOriginalAudioItem_i(Fl_Menu_*, void*) {
  DisplayInputSound();
}
void UserInterface::cb_mShowOriginalAudioItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowOriginalAudioItem_i(o,v);
}

inline void UserInterface::cb_mShowSinTracksItem_i(Fl_Menu_*, void*) {
  DisplaySinusoidalTracks();
}
void UserInterface::cb_mShowSinTracksItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSinTracksItem_i(o,v);
}

inline void UserInterface::cb_mShowSpectrumAndPeaksItem_i(Fl_Menu_*, void*) {
  DisplaySpectrumAndPeaks();
}
void UserInterface::cb_mShowSpectrumAndPeaksItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSpectrumAndPeaksItem_i(o,v);
}

inline void UserInterface::cb_mShowSinusoidalSpectrumItem_i(Fl_Menu_*, void*) {
  DisplaySinusoidalSpectrum();
}
void UserInterface::cb_mShowSinusoidalSpectrumItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowSinusoidalSpectrumItem_i(o,v);
}

inline void UserInterface::cb_mShowResidualSpectrumItem_i(Fl_Menu_*, void*) {
  DisplayResidualSpectrum();
}
void UserInterface::cb_mShowResidualSpectrumItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mShowResidualSpectrumItem_i(o,v);
}

inline void UserInterface::cb_mSynthesizedAudioItem_i(Fl_Menu_*, void*) {
  DisplaySynthesizedAudio();
}
void UserInterface::cb_mSynthesizedAudioItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mSynthesizedAudioItem_i(o,v);
}

inline void UserInterface::cb_mSynthesizedSinusoidalItem_i(Fl_Menu_*, void*) {
  DisplaySynthesizedSinusoidal();
}
void UserInterface::cb_mSynthesizedSinusoidalItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mSynthesizedSinusoidalItem_i(o,v);
}

inline void UserInterface::cb_mSynthesizedResidualItem_i(Fl_Menu_*, void*) {
  DisplaySynthesizedResidual();
}
void UserInterface::cb_mSynthesizedResidualItem(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mSynthesizedResidualItem_i(o,v);
}

inline void UserInterface::cb_About_i(Fl_Menu_*, void*) {
  AboutWindow();
}
void UserInterface::cb_About(Fl_Menu_* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_About_i(o,v);
}

Fl_Menu_Item UserInterface::menu_mMenuBar[] = {
 {"File", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Load Configuration...", 0,  (Fl_Callback*)UserInterface::cb_Load, 0, 0, 0, 0, 12, 0},
 {"Edit Configuration...", 0,  (Fl_Callback*)UserInterface::cb_Edit, 0, 0, 0, 0, 12, 0},
 {"Store Configuration...", 0,  (Fl_Callback*)UserInterface::cb_Store, 0, 0, 0, 0, 12, 0},
 {"Exit", 0x40071,  (Fl_Callback*)UserInterface::cb_Exit, 0, 0, 0, 0, 12, 0},
 {0},
 {"SMS Analysis", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Analyze", 0x40061,  (Fl_Callback*)UserInterface::cb_mAnalyze, 0, 1, 0, 0, 12, 0},
 {"Load...", 0,  (Fl_Callback*)UserInterface::cb_Load1, 0, 0, 0, 0, 12, 0},
 {"Store...", 0,  (Fl_Callback*)UserInterface::cb_mStoreAnalysisData, 0, 1, 0, 0, 12, 0},
 {"Melody", 0,  0, 0, 65, 0, 0, 12, 0},
 {"Analyze", 0,  (Fl_Callback*)UserInterface::cb_mMelodyAnalyze, 0, 0, 0, 0, 12, 0},
 {"Store", 0,  (Fl_Callback*)UserInterface::cb_mMelodyStore, 0, 1, 0, 0, 12, 0},
 {0},
 {"Display Sinusoidal Tracks", 0,  (Fl_Callback*)UserInterface::cb_mSinTracksDisplay, 0, 1, 0, 0, 12, 0},
 {0},
 {"SMS Transformation", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Load...", 0,  (Fl_Callback*)UserInterface::cb_Load2, 0, 0, 0, 0, 12, 0},
 {"Apply", 0,  (Fl_Callback*)UserInterface::cb_mDoTransformation, 0, 1, 0, 0, 12, 0},
 {0},
 {"SMS Synthesis", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Synthesize", 0x40073,  (Fl_Callback*)UserInterface::cb_Synthesize, 0, 0, 0, 0, 12, 0},
 {"Store Results", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Sound", 0,  (Fl_Callback*)UserInterface::cb_Sound, 0, 0, 0, 0, 12, 0},
 {"Sinusoidal", 0,  (Fl_Callback*)UserInterface::cb_Sinusoidal, 0, 0, 0, 0, 12, 0},
 {"Residual", 0,  (Fl_Callback*)UserInterface::cb_Residual, 0, 0, 0, 0, 12, 0},
 {0},
 {0},
 {"View", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Original Audio", 0,  (Fl_Callback*)UserInterface::cb_mShowOriginalAudioItem, 0, 0, 0, 0, 12, 0},
 {"Analysis Results", 0,  0, 0, 64, 0, 0, 12, 0},
 {"SinusoidalTracks", 0,  (Fl_Callback*)UserInterface::cb_mShowSinTracksItem, 0, 0, 0, 0, 12, 0},
 {"Frame Data", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Spectrum and Peaks", 0,  (Fl_Callback*)UserInterface::cb_mShowSpectrumAndPeaksItem, 0, 0, 0, 0, 12, 0},
 {"Sinusoidal Spectrum", 0,  (Fl_Callback*)UserInterface::cb_mShowSinusoidalSpectrumItem, 0, 0, 0, 0, 12, 0},
 {"Residual Spectrum", 0,  (Fl_Callback*)UserInterface::cb_mShowResidualSpectrumItem, 0, 0, 0, 0, 12, 0},
 {0},
 {0},
 {"Synthesis Results", 0,  0, 0, 64, 0, 0, 12, 0},
 {"Synthesized Audio", 0,  (Fl_Callback*)UserInterface::cb_mSynthesizedAudioItem, 0, 0, 0, 0, 12, 0},
 {"Synthesized Sinusoidal", 0,  (Fl_Callback*)UserInterface::cb_mSynthesizedSinusoidalItem, 0, 0, 0, 0, 12, 0},
 {"Synthesized Residual Sound", 0,  (Fl_Callback*)UserInterface::cb_mSynthesizedResidualItem, 0, 0, 0, 0, 12, 0},
 {0},
 {0},
 {"Help", 0,  0, 0, 64, 0, 0, 12, 0},
 {"About", 0,  (Fl_Callback*)UserInterface::cb_About, 0, 0, 0, 0, 12, 0},
 {0},
 {0}
};
Fl_Menu_Item* UserInterface::mAnalyze = UserInterface::menu_mMenuBar + 7;
Fl_Menu_Item* UserInterface::mStoreAnalysisData = UserInterface::menu_mMenuBar + 9;
Fl_Menu_Item* UserInterface::mMelodySM = UserInterface::menu_mMenuBar + 10;
Fl_Menu_Item* UserInterface::mMelodyAnalyze = UserInterface::menu_mMenuBar + 11;
Fl_Menu_Item* UserInterface::mMelodyStore = UserInterface::menu_mMenuBar + 12;
Fl_Menu_Item* UserInterface::mSinTracksDisplay = UserInterface::menu_mMenuBar + 14;
Fl_Menu_Item* UserInterface::mDoTransformation = UserInterface::menu_mMenuBar + 18;
Fl_Menu_Item* UserInterface::mSynthesize = UserInterface::menu_mMenuBar + 20;
Fl_Menu_Item* UserInterface::mStoreOutputs = UserInterface::menu_mMenuBar + 22;
Fl_Menu_Item* UserInterface::mViewMenuItem = UserInterface::menu_mMenuBar + 28;
Fl_Menu_Item* UserInterface::mShowOriginalAudioItem = UserInterface::menu_mMenuBar + 29;
Fl_Menu_Item* UserInterface::mShowSinTracksItem = UserInterface::menu_mMenuBar + 31;
Fl_Menu_Item* UserInterface::mShowSpectrumAndPeaksItem = UserInterface::menu_mMenuBar + 33;
Fl_Menu_Item* UserInterface::mShowSinusoidalSpectrumItem = UserInterface::menu_mMenuBar + 34;
Fl_Menu_Item* UserInterface::mShowResidualSpectrumItem = UserInterface::menu_mMenuBar + 35;
Fl_Menu_Item* UserInterface::mSynthesizedAudioItem = UserInterface::menu_mMenuBar + 39;
Fl_Menu_Item* UserInterface::mSynthesizedSinusoidalItem = UserInterface::menu_mMenuBar + 40;
Fl_Menu_Item* UserInterface::mSynthesizedResidualItem = UserInterface::menu_mMenuBar + 41;
Fl_Menu_Item* UserInterface::mHelpItem = UserInterface::menu_mMenuBar + 44;

inline void UserInterface::cb_mCounter_i(Fl_Counter*, void*) {
  ChangeFrame();
}
void UserInterface::cb_mCounter(Fl_Counter* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_mCounter_i(o,v);
}

inline void UserInterface::cb_mWindow2_i(Fl_Window*, void*) {
  delete mWindow2;
mWindow2=NULL;
}
void UserInterface::cb_mWindow2(Fl_Window* o, void* v) {
  ((UserInterface*)(o->user_data()))->cb_mWindow2_i(o,v);
}

UserInterface::UserInterface() {
  Fl_Window* w;
  { Fl_Window* o = mWindow = new Fl_Window(872, 548, "SMS Analysis/Synthesis Application | MTG-UPF (Barcelona)");
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 0, 872, 21);
      o->end();
    }
    { Fl_Menu_Bar* o = mMenuBar = new Fl_Menu_Bar(0, 0, 872, 21);
      o->box(FL_THIN_UP_BOX);
      o->labelsize(13);
      o->textsize(12);
      o->menu(menu_mMenuBar);
    }
    { Fl_Counter* o = mCounter = new Fl_Counter(330, 525, 190, 20, "Frame ");
      o->box(FL_THIN_UP_BOX);
      o->labelsize(12);
      o->minimum(0);
      o->maximum(0);
      o->step(1);
      o->callback((Fl_Callback*)cb_mCounter);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Group* o = new Fl_Group(0, 25, 870, 495);
      { Fl_Smart_Tile* o = mSmartTile = new Fl_Smart_Tile(0, 25, 870, 495);
        o->minsize(80);
      }
      o->end();
      Fl_Group::current()->resizable(o);
    }
    mWindow2=NULL;
    o->end();
  }
}

void UserInterface::AboutWindow() {
  Fl_Window* w;
  { Fl_Window* o = mWindow2 = new Fl_Window(417, 100, "About this program...");
    w = o;
    o->box(FL_ENGRAVED_BOX);
    o->labeltype(FL_NORMAL_LABEL);
    o->labelsize(10);
    o->callback((Fl_Callback*)cb_mWindow2, (void*)(this));
    { Fl_Box* o = new Fl_Box(85, 15, 265, 20, "SMS Analysis/Synthesis Application");
      o->labelfont(3);
      o->labelsize(12);
    }
    { Fl_Box* o = new Fl_Box(85, 40, 265, 20, "by MTG - IUA - UPF (Barcelona, Spain)");
      o->labelfont(2);
      o->labelsize(12);
    }
    new Fl_Box(360, 15, 50, 60, "logos/iua.xpm");
    { Fl_Box* o = new Fl_Box(90, 65, 260, 20, "please visit us at http://www.iua.upf.es/mtg for more info");
      o->labelfont(2);
      o->labelsize(11);
    }
    new Fl_Box(10, 20, 75, 55, "logos/mtg.xpm");
    mWindow2->show();
    o->set_modal();
    o->end();
  }
}
